### ISSUE TITLE
Spring : Accessing BindingStatus Errors outside of a form tag

### ISSUE THREAD

**Issue by tdeverdiere** [thymeleaf/thymeleaf-spring#10]
This enhancement comes from the discussion : 
http://forum.thymeleaf.org/Spring-MVC-Displaying-Validation-Errors-outside-form-td4025301.html

I would like to have the same behaviour than the Spring tag :
spring:hasBindErrors

In order to change the title of my page depending on the fact there are errors or not in the form fields.

**Comment by danielfernandez** [comment]
This has been implemented as follows:

**Inside a form**

Inside a form, error messages can be output in the usual way (plus the options added by #21):

``` html
<form th:object="${myForm}">

    <div th:errors="*"></div>
    <div th:errors="all"></div>
    <div th:errors="global"></div>
    <div th:errors="*{*}"></div>
    <div th:errors="*{all}"></div>
    <div th:errors="*{global}"></div>
    <div th:errors="*{name}"></div>
    ...
    <div th:if="${#fields.hasErrors('*')}"></div>
    <div th:if="${#fields.hasErrors('all')}"></div>
    <div th:if="${#fields.hasErrors('global')}"></div>
    <div th:if="${#fields.hasErrors('*{*}')}"></div>
    <div th:if="${#fields.hasErrors('*{all}')}"></div>
    <div th:if="${#fields.hasErrors('*{global}')}"></div>
    <div th:if="${#fields.hasErrors('*{name}')}"></div>
    ...
</form>
```

**Outside a form**

But now, these errors can be accessed from outside with `${...}` expressions, by using the bound form object's name like this:
- Using the form bean's name only: `${myForm}`, returns the error messages _globally_ associated to that form-backing object, this is, not associated to a specific field. Equivalent to `global` or `*{global}` inside a form.
- Using the form bean's name plus the name of a field: `${myForm.date}`, returns the error messages associated to that specific field of the form. Equivalent to `*{date}` inside a form.
- Using the form bean's name plus the wildcard symbol: `${myForm.*}`, returns the error messages associated both to the form in a _global_ manner (no specific field) and also to any of its fields. Equivalent to `*`, `all`, `*{*}` and `*{all}` inside a form.

``` html

<div th:errors="${myForm}"></div>
<div th:errors="${myForm.date}"></div>
<div th:errors="${myForm.*}"></div>

<div th:if="${#fields.hasErrors('${myForm}')}"></div>
<div th:if="${#fields.hasErrors('${myForm.date}')}"></div>
<div th:if="${#fields.hasErrors('${myForm.*}')}"></div>

<form th:object="${myForm}">
    ...
</form>
```

**Comment by danielfernandez** [comment]
Updated 2.1.0-SNAPSHOT

**Comment by Jarvis2704** [comment]
Can you explain what do you mean by 'form bean's name'?
