### ISSUE TITLE
Wrong documentation on ThymeleafView

### ISSUE THREAD

**Issue by mmoayyed** [thymeleaf/thymeleaf-spring#101]
Docs indicate:

```
<bean name="main" class="org.thymeleaf.spring4.view.ThymeleafView">
  <property name="staticVariables">
    <map>
      <entry key="footer" value="Some company: &lt;b&gt;ACME&lt;/b&gt;" />
    </map>
  </property>
</bean>
```

which is of course not possible in 2.1.4 and wrong. The ctor is marked as protected.

See http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html

**Comment by danielfernandez** [comment]
You mean the _setter_? It's public... https://github.com/thymeleaf/thymeleaf-spring/blob/2.1-master/thymeleaf-spring4/src/main/java/org/thymeleaf/spring4/view/AbstractThymeleafView.java#L383-L390
