### ISSUE TITLE
First new line character is removed when use <textarea th:field="...">

### ISSUE THREAD

**Issue by kazuki43zoo** [thymeleaf/thymeleaf-spring#103]
When first character of input value is new line character, `<textarea th:field="...">` is output the HTML as follow:

``` html
<textarea id="text" th:field="*{text}"></textarea>
```

e.g.) input value at textarea is `"<CRLF>input value"`

``` html
<textarea id="text" name="text">
input value</textarea>
```

When render the above HTML on Web Browser(Chrome, Firefox, Safari, IE ...), first new line character is removed from User Interface.
On an Web Browser,`"<CRLF>input value"` is render same with `"input value"` (without `<CRLF>`).
Probably, this case should be output the HTML as follow:
(Append new line character after `<textarea>` start tag)

``` html
<textarea id="text" name="text">

input value</textarea>
```

I found a workaround as follow. However child text(`<span th:text="*{text}" th:remove="tag"></span>`) has been displayed  into a textarea when open as prototype html file on Web Browser.

``` html
<textarea id="text" name="text">
<span th:text="*{text}" th:remove="tag"></span></textarea>
```

Can you resolve this issue as library improvement ?
Are there solutions for this issue already ?

**Note:**
`<form:textarea>` jsp taglib provided by Spring have same problem. However, it is fixed at Spring 4.2.6.RELEASE(next maintenance release).
https://jira.spring.io/browse/SPR-13503

**Comment by danielfernandez** [comment]
Fixed in the 2.1 branch by means of #104

**Comment by danielfernandez** [comment]
References:
- Spring JIRA: SPR-13503 https://jira.spring.io/browse/SPR-13503
- HTML 4.01 spec: line breaks https://www.w3.org/TR/html401/appendix/notes.html#notes-line-breaks
- HTML5 spec: the `textarea` element https://www.w3.org/TR/html5/forms.html#the-textarea-element
- Current Apache Wicket implementation https://github.com/apache/wicket/blob/9329aaea1fbfe2c6f517e53491a6f767b1702932/wicket-core/src/main/java/org/apache/wicket/markup/html/form/TextArea.java#L62-L84

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`

**Comment by kazuki43zoo** [comment]
Hi @danielfernandez , Thanks for fix!!
