### ISSUE TITLE
Null field for textarea dies in SpringTextareaFieldTagProcessor

### ISSUE THREAD

**Issue by abs0** [thymeleaf/thymeleaf-spring#108]
textarea fails if the th:field is null, while input works fine.

Fails:
`<textarea th:field="${activityData.notes}" rows="5" cols="50" th:maxlength="${limits.notesLength}" class="form-control"/>`

Works:
`<input th:field="${activityData.notes}" rows="5" cols="50" th:maxlength="${limits.notesLength}" class="form-control"/>`

Actual exception was:

`Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.spring4.processor.SpringTextareaFieldTagProcessor' (template: "activity/editActivity" - line 58, col 21)
        at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:115)
`
- Thymeleaf 3.0.0.BETA03
- Spring 4.2.6.RELEASE
- Running in wildfly 9

**Comment by danielfernandez** [comment]
This was an issue in BETA03. It should be fixed in 3.0.0.RELEASE, could you please try the new version?

**Comment by abs0** [comment]
Many thanks - confirmed fixed. I had only downloaded BETA3 on Friday but forgot to check for a new version.
