### ISSUE TITLE
Non-disabled checkbox issue with Bootstrap

### ISSUE THREAD

**Issue by tedwards-rogue** [thymeleaf/thymeleaf-spring#111]
After presenting this to the Thymeleaf forum, it seems this may be the appropriate place for this issue.

Although I have found similar issues and solution on the web, I have not find the specific answer to resolve this problem. 

A basic Bootstrap overlay of a checkbox requires the input tags to be inside of the labels. 

An example would be this: 
`<label class="checkbox"><input class="checked-agree" type="checkbox" name="checkbox" />I agree to the Terms of Service</label>`

Based on examples and other input, I would use the following using Thymeleaf: 
`<label th:for="${#ids.next('terms')}" class="checkbox"><input th:field="*{terms}" class="checked-agree" type="checkbox" name="checkbox" />I agree to the Terms of Service</label>`

Unfortunately the resulting output in HTML (shown below) puts two inputs between the label tags and causes the overlay to not work and therefore the checkbox will not click on and off. 

```
<label class="checkbox" for="terms1">
<input class="checked-agree" type="checkbox" name="terms" id="terms1" value="true">
<input type="hidden" name="_terms" value="on">
I agree to the Terms of Service</label>
```

My expectations is that I could freely use Thymeleaf and Bootstrap without this type of issue. This may be happening to other UI elements too, but checkbox is the only one I have confirmed.

It seems this issue is caused by the following:
https://github.com/thymeleaf/thymeleaf-spring/blob/3.0-master/thymeleaf-spring4/src/main/java/org/thymeleaf/spring4/processor/SpringInputCheckboxFieldTagProcessor.java#L114-L142

**Comment by tedwards-rogue** [comment]
For a quick experiment, I wanted to see what happened if the hidden input was placed before the other input element. I edited the generated HTML by hand with firebug to make it look like this:

```
<label class="checkbox" for="terms1">
<input type="hidden" name="_terms" value="on">
<input class="checked-agree" type="checkbox" name="terms" id="terms1" value="true">
<i></i>I agree to the <a href="#" data-toggle="modal" data-target="#termsModal">Terms of Service</a></label>
```

In this situation, the Bootstrap styled checkbox worked successfully (at least in Chrome). 

Unfortunately my skills are not at a level where I feel comfortable experimenting with modifying he SpringInputCheckboxFieldTagProcessor.java file, but my assumption is there would be a way to generate the hidden tag first instead of after the element.

**Comment by danielfernandez** [comment]
Could you please elaborate on the way this Bootstrap overlay works, specifically the javascript/CSS code that selects the `<input>` to work with?

Adding a hidden input to checkboxes is a fairly standard behaviour for server-side form binding (unchecked checkboxes are never sent to the server, so that's the way the server knows the checkbox was **unchecked** as opposed to **disabled** or simply **not present**). In fact, Thymeleaf here merely mimics the behaviour of the Spring JSP tag library, which creates these `<input>` tags in the same order.

At first sight it looks like a bug (or at least a bad selection behaviour) in the involved selection code. Is there a way you could share the specific fragment and its origin?

**Comment by danielfernandez** [comment]
Maybe related to something like flatlogic/awesome-bootstrap-checkbox#14

**Comment by tedwards-rogue** [comment]
Daniel, thanks for your input. When I did some original research I did stumble upon the link you submitted above. This time around I reviewed it a little deeper. 

The first comment I should make is that this is not a Bootstrap related issue. Bootstrap uses the browser/OS standard checkboxes. In researching for this issue, I discovered that the CSS in questions is in the theme I have purchased (shall not name at this time; purchased product). Their theme uses a standard method to create "pretty" checkboxes () using CSS wizardry and a simple `<i>` tag. I have seen this done in several themes available. 

Example of the styled checkbox: ![screen shot 2016-05-31 at 9 09 57 am](https://cloud.githubusercontent.com/assets/19335115/15681912/11ca81e2-2710-11e6-8a52-670f3ae13886.png)

The CSS from the theme vendor looks like this (there are more CSS statements in the file, but this one seemed to be the most relevant one):
`.checkbox input+i:after {
    content: '\f00c';
    top: 0;
    left: 0px;
    width: 15px;
    height: 15px;
    font: normal 12px/16px FontAwesome;
    text-align: center;
}`

I am not a CSS master in anyway, but it seems that the `<i>` tag and the checkbox content (\f00c) is being applied to the hidden input tag generated by Thymeleaf. I tried a few CSS changes to get the style to apply to the non hidden input tag, but was not successful.

**Comment by tedwards-rogue** [comment]
Created an example at https://codepen.io/tledwar/pen/ZOYWvr

This shows that adding a hidden field causes a styled checkbox to not display correctly. Of course this is probably a CSS issue more than anything but I am hopeful we can come up with an example which works for Thymeleaf.

Please note that this example is more in line with the flatlogic/awesome-bootstrap-checkbox#14 example previously given and not the html for which I opened the issue with.

**Comment by danielfernandez** [comment]
In your codepen, replacing all the `+` combinators with `~` makes it work OK. Would that be an issue for you? 

In flatlogic/awesome-bootstrap-checkbox#1 they mention compatibility issues in mobile devices as a reason for sticking to `+` in favour of `~`, but looking at the mozilla pages they link this seems to have improved a lot since 2014…

**Comment by tedwards-rogue** [comment]
I had tried that earlier in my actual code, but I went back to codepen and sure enough it worked. But that is raw HTML and not Thymeleaf, so I went ahead and changed my example code.

To match up with the working codepen, the input needs to be before the label. So...
`<div>
    <input th:field="*{terms}" class="checked-agree" type="checkbox" name="checkbox" />
    <label th:for="${#ids.next('terms')}" class="checkbox">I agree to the Terms of Service</label>
</div>`

But now look what happens:
`<div>
    <input class="checked-agree" type="checkbox" name="terms" id="terms1" value="true">
    <input type="hidden" name="_terms" value="on">
    <label class="checkbox" for="terms2">I agree to the Terms of Service</label>
</div>`

Unless I am using Thymeleaf incorrectly in this situation, it has improperly calculated the ids between the input and label (terms1 vs terms2).

**Comment by danielfernandez** [comment]
If now your label is being processed _after_ the `<input>` to which the id is assigned, you should not be using `#ids.next()`, but instead `#ids.prev()`.

**Comment by tedwards-rogue** [comment]
That would make complete sense! Thank you for help in researching this topic.
