### ISSUE TITLE
Allow delaying first output until processing completely finishes

### ISSUE THREAD

**Issue by dtrunk90** [thymeleaf/thymeleaf-spring#113]
Streamlined execution flow causes a partially rendered template containing the error page with HTTP status code 200 on exceptions at view layer. This behavior is nonsatisfying for such a common use-case.

The servlet dispatcher should forward to the error page with HTTP status code 500 as it was the case in Thymeleaf < 3 already.

Based on the discussion [here](http://forum.thymeleaf.org/Thymeleaf-3-Exception-Handling-td4029725.html) you need to write your own implementation of `ITemplateEngine` when using Thymeleaf in conjunction with Spring MVC which is an ugly workaround.

Maybe putting a flag into `SpringTemplateEngine` to make it configurable could be a better solution.

**Comment by michaelhaessig** [comment]
I stumbled across the same issue.  as @dtrunk90 said , there needs to be a cleaner solution for this problem..

**Comment by danielfernandez** [comment]
A more general solution to this would be to move the call to the template engine object at the end of `ThymeleafView#renderFragment(...)` to a separate method that could be more easily overridden by users' extensions of `ThymeleafView`.

This would allow users to configure the way the template engine is actually called (after all the parameters have been resolved and computed), and even apply any pre- or post-processing operations that might be needed.

This specific scenario would be covered therefore by creating an extension of `ThymeleafView` that calls the `process(...)`methods returning `String`, then write the result into `response.getWriter()` in a separate step.

**Comment by RiZKiT** [comment]
Another frontend aggregation/transclusion solution ([Tailor](https://github.com/zalando/tailor)) uses the term "[primary fragment](https://github.com/zalando/tailor#fragment-attributes)", the HTTP status code of that fragment defines the status code of the whole page.

Related issues which are maybe interesting: https://github.com/zalando/tailor/issues?utf8=%E2%9C%93&q=is%3Aissue+primary

**Comment by odrotbohm** [comment]
@danielfernandez – Do you think what you suggested is a candidate for actual implementation. If the suggested changes were in place, `ThymeleafViewResolver` could expose a simple switch to resort to the old behavior of in-memory rendering and in turn be exposed via e.g. a Spring Boot application property.

**Comment by odrotbohm** [comment]
Oh, and it would be cool if the error scenario could be documented in the [migration guide](https://www.thymeleaf.org/doc/articles/thymeleaf3migration.html) as it's a problem, that doesn't actually exist on Thymeleaf 2. Possible workarounds should be documented here as well. Besides the tweak to the server side, one other thing that came to mind was to equip the error page with some JavaScript that would cause a page reload to the actual error page, so that the error content basically get's "unwrapped".

**Comment by dsyer** [comment]
Another option is to increase the buffer size in the `ServletResponse`. It's not brilliant, but it works if you know an upper bound on the size of your responses.

**Comment by danielfernandez** [comment]
Additionally, this could be adjusted in application code by creating a `Filter` that wraps the `HttpServletResponse` and buffers all output until the reponse `PrintWriter` is closed. Using a filter could even allow the application of this mechanism per-URL. This could be enough for specific applications having this issue, as I hope this shouldn't be a common scenario.

To be honest, I'm still struggling with myself as to whether it makes sense to add a *feature* that would willingly degrade Thymeleaf's performance to the point that it could actually turn the web server useless. Performance was by far the main criticism of Thymeleaf 2.x and the main reason Thymeleaf 3 was a complete engine rewrite. 

Actually, there could be scenarios in which doing a complete processing of the template before sending to browser could be worse memory-wise in Thymeleaf 3 than it was in Thymeleaf 2:  Thymeleaf 2 did all the processing in memory in the form of an object tree (a DOM), and then started to output the entire template result tree towards the webserver buffers, rendering objects into Strings as the tree was traversed (so writing to buffers was very fast); however Thymeleaf 3 does not have a DOM, so it would need to actually perform the entire _HTML rendering_ of the template result into some kind of string buffer, and then write the entire rendered HTML to the web server buffers. So it will come down to whether having an entire DOM tree in memory takes more memory or less than a large String buffer. In general I have a tendency to be very wary of having large amounts of duplicated text in memory, but it's true that most probably the string buffers will require less space in most scenarios, maybe not all.

And I understand the effects in browser rendering, but partial buffer flushing during template execution is how server HTML rendering has typically worked in the past IMHO (e.g. JSP), so it's difficult for me to not see this as an issue at the client code...

Not that this means that Thymeleaf could not offer a way to ease the pain, that's true. But still...

**Comment by odrotbohm** [comment]
I am not even arguing which one is better and am fine with Thymeleaf defaulting to streaming and having a strong opinion that this is the better approach. All I'm arguing is, that there should be an easy way to get back to the "old mode" of exception handling (i.e. exceptions trigger a forward to the error page under all circumstances) as that allows users to decouple both problems: if they were fine with in-memory rendering on TL2, they probably are with TL3 *for a start*. People starting with Thymeleaf 3 don't have to be bothered with this. But migrations could now move to TL3 first and then spend dedicated time to tackle this problem. As it stands today, projects running into this problem will have a hard time to move to TL3 (or Spring Boot 2.0 transitively) at all.

**Comment by danielfernandez** [comment]
Okay, I see your point. I have to admit from the standpoint of migrations it makes a bit more sense to me.

**Comment by danielfernandez** [comment]
This has been implemented by means of a flag called `producePartialOutputWhileProcessing`, with default value `true`, that can be configured with its corresponding setter and getter method both at the `ThymeleafViewResolver` (for an application-wide setting) and at `ThymeleafView` objects (for template-specific setting).

When set to `false`, Thymeleaf will buffer the entire produced output until processing completely finishes and only then output it as a single chunk to the web server's output buffers.

First (very informal) tests with very large HTML documents show no significative difference in time-to-last-result times with concurrent load = 1, but obviously huge differences in time-to-first-result times and memory consumption, so this should turn the web server very sensitive to increases in concurrent load.

**Comment by danielfernandez** [comment]
Already in `3.0.10-SNAPSHOT`

**Comment by nhatanhmc** [comment]
@danielfernandez can u give me some example for using producePartialOutputWhileProcessing, I'm getting a trouble in here, I can't catch exception of thymeleaf to rediect to custom error page > < can you help me ?

**Comment by nhatanhmc** [comment]
> @danielfernandez can u give me some example for using producePartialOutputWhileProcessing, I'm getting a trouble in here, I can't catch exception of thymeleaf to rediect to custom error page > < can you help me ?

ok I forgot set order for viewResolver in my thymeleaf config so the producePartialOutputWhileProcessing is not work =))
