### ISSUE TITLE
Exception evaluating SpringEL expression

### ISSUE THREAD

**Issue by JstMagic** [thymeleaf/thymeleaf-spring#115]
I received the error below when i added crf token to my login page

_`**Exception evaluating SpringEL expression: "csrf.parameterName"**`_

**Console error**

```
 _ERROR [org.springframework.boot.context.web.ErrorPageFilter] (default task-1) Forwarding to error page from request [/login] due to exception [Exception evaluating SpringEL expression: "_csrf.parameterName" (template: "login" - line 44,
col 50)]: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "_csrf.parameterName" (template: "login" - line 44, col 50)

Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1072E:(pos 0): An exception occurred whilst evaluating a compiled expression
        at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:262)
        at org.thymeleaf.spring4.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:257)_
```

**Code**
_`<input type="hidden" th:name="${ _csrf.parameterName }" th:value="${_csrf.token }" />`_
- The weird issue happens when I logout and then try to login again in my application using the path "/logout" and "/login"
- When i restart the server and I login the first time it works but the moment i logout and try to login again then issue appears and I am unable to login due to the error until i restart my application.

**Fix and work around**
- Downgraded from thymeleaf spring 4 3.0.0 beta 2 to 3.0.0

**Before**

```
_<dependency>
           <groupId>org.thymeleaf</groupId>
           <artifactId>thymeleaf</artifactId>
            <version>3.0.0.BETA02</version>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf-spring4</artifactId>
            <version>3.0.0.BETA02</version>
        </dependency>_
```

 **now** 

```
_<dependency>
             <groupId>org.thymeleaf</groupId>
             <artifactId>thymeleaf</artifactId>
             <version>3.0.0.RELEASE</version>
         </dependency>
         <dependency>
            <groupId>org.thymeleaf</groupId>
             <artifactId>thymeleaf-spring4</artifactId>
            <version>3.0.0.RELEASE</version>
        </dependency>_
```

**Comment by danielfernandez** [comment]
Sorry, I cannot understand your issue here... you say you _downgraded_ from `3.0.0.BETA02`, which is a _beta_ version, to `3.0.0.RELEASE`, which is the stable (i.e. non-beta) version? Is this corrrect? If so, how can this be a _downgrade_?

Your issue looks quite a lot like something we fixed between BETA02 and BETA03... so it makes sense it works alright in the stable version…
