### ISSUE TITLE
Spring-Standard-Dialect.xml links to tutorials/2.1 instead of 3.0

### ISSUE THREAD

**Issue by maxxyme** [thymeleaf/thymeleaf-spring#124]
In this file: https://github.com/thymeleaf/thymeleaf-spring/blob/3.0-master/thymeleaf-spring4/src/main/resources/org/thymeleaf/xml/thymeleaf-spring4/Spring-Standard-Dialect.xml

the links found point to http://www.thymeleaf.org/doc/tutorials/2.1/thymeleafspring.html instead of http://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html

**Comment by ultraq** [comment]
Just like the other issue you opened against another repo, there's a version of these files in the `3.0-dev` branch that have the updated URLs, but haven't yet been merged to master.  They should be before the next release.

**Comment by maxxyme** [comment]
OK, I should've check the dev branch too. Sorry for that.
