### ISSUE TITLE
Bean name resolution

### ISSUE THREAD

**Issue by Dazzel** [thymeleaf/thymeleaf-spring#131]
You got this classes:

Interface:
`public interface ExampleService {}`

Implementing class:
`
@Service
public class ExampleServiceImpl implements ExampleService {}`

Usage in Spring:
`@Resource private ExampleService exService;`

Given the usage in Spring one would suspect that you'll use the bean the same way in Thymeleaf, by its interface name: `${@exampleService.}` but you have to use it by the implementing class name: `${@exampleServiceImpl.}`.

It would be better if this behaviour is consistent with the Spring way without overriding the bean name in the annotation.

**Comment by danielfernandez** [comment]
Thymeleaf does not name Spring beans, nor has any influence on their naming or how they are accessed. That is entirely Spring's responsibility, so there is no difference in how your beans would be accessed by name using Thymeleaf or not using it.

All Thymeleaf does is to simply execute SpEL (Spring EL) expressions, and it's Spring's EL engine who is in charge of performing all bean accessing. Thymeleaf does not even know which beans are registered. So I'm afraid there is nothing Thymeleaf can do here.
