### ISSUE TITLE
Thymeleaf 3.0.3 and Spring Boot 1.2.6

### ISSUE THREAD

**Issue by LeonardoRamos** [thymeleaf/thymeleaf-spring#134]
Hello, is there a way to use the newest version of Thymeleaf (3.0.4) along with Spring Boot 1.2.6?
If so, is there any workaround I should do to accomplish this?

Thank you!

**Comment by ultraq** [comment]
The latest Spring Boot docs have instructions for using Thymeleaf 3, so have you tried those to see if they work even if they're not Spring Boot 1.2.6 specific? http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/htmlsingle/#howto-use-thymeleaf-3

**Comment by LeonardoRamos** [comment]
Hi, I was able to successfully use the latest version with Spring Boot 1.2.6 following these instructions: https://gist.github.com/seanhinkley/6eab2130ceea857c160b
Everything works fine!
Thanks for the response!
