### ISSUE TITLE
fragment reference with expressions

### ISSUE THREAD

**Issue by lizhiyuan09** [thymeleaf/thymeleaf-spring#135]
i define a fragment,and reference it with expressions,but en exception happens.
common.html
```
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
<meta charset="UTF-8">
</head>
<title>Insert title here</title>
</head>
<body>
	<div th:fragment="proposals">
		<h1>proposals fragment</h1>
	</div>
</body>
</html>
```
a piece in index.html 
```
<div th:replace=${tName} :: ${fName}>
 </div>
```

console:
`Error resolving fragment: "${tName}": template or fragment could not be resolved `

**Comment by danielfernandez** [comment]
Please note this code is invalid:
```html
<div th:replace=${tName} :: ${fName}>
</div>
```
I don't know what version of Thymeleaf you are using, but 2.1 would not parse this unless you are using the `LEGACYHTML5` template mode (which will autobalance your tags and autocorrect this type of code in not-entirely-predictable manners). In Thymeleaf 3.0 the HTML spec will apply and the `th:replace` attribute will have value `${tName}`, and then two other attributes will be parsed for the tag with names `::` and `${fName}`, both with no value.

So please fix the attribute value by surrounding it with quotes:
```html
<div th:replace="${tName} :: ${fName}">
</div>
```
And make sure you actually have a `tName` variable in the context which value can be resolved to the name of a template. Other than that, your code should work.

**Comment by lizhiyuan09** [comment]
it works,thanks
