### ISSUE TITLE
Can I use thymeleaf with webflux.fn?

### ISSUE THREAD

**Issue by xmlking** [thymeleaf/thymeleaf-spring#141]
can't find any examples or documentation on how to use #webflux.fn with model and #thymeleaf
Is it possible to use thymeleaf with spring 5 webflux functional style routers ?

**Comment by danielfernandez** [comment]
Sure, you can use the `render(...)` method in `ServerResponse.BodyBuilder` for rendering any Spring `View`, including Thymeleaf's.

Your handler method could look for example like:

```java
public Mono<ServerResponse> index(final ServerRequest request) {
    final Map<String,Object> model =
            Collections.singletonMap("salute", "Hello world from WebFlux.fn");
    return ServerResponse.ok().contentType(MediaType.TEXT_HTML).render("index", model);
}
```

There, `"index"` is the name of your template. If this is a Spring Boot application (and you are using the `spring-boot-starter-thymeleaf` starter) it would live as usual in `src/main/resources/templates`.

And then you'd only have to reference your `Handler::index` method from your `Router` class.

**Comment by somasekharnekkalapudi** [comment]
Not able to access the "salute" attribute in index.html. Any examples?

<div> th:text="${salute}"</div>
