### ISSUE TITLE
Strange behavior with url path variable and param at once in form th:action

### ISSUE THREAD

**Issue by sushiljic** [thymeleaf/thymeleaf-spring#143]
With anchor tag
`<a class="btn btn-primary" th:href="@{/bill-job/{id}(id=${trigger.triggerKey},action=${#bools.isTrue(trigger.isPaused)?'resume':'pause'})}">Proceed</a>`

Output will be
`http://localhost:8090/bill-job/MonthlyBillingRobot.monthlyChargeTriggerFor24?action=resume`
![image](https://user-images.githubusercontent.com/5524563/26936753-36c64742-4c8f-11e7-80bd-1a074382d7dd.png)

Whereas with form th:action
`<form th:action="@{/bill-job/{id}(id=${trigger.triggerKey},action=${#bools.isTrue(trigger.isPaused)?'resume':'pause'})}">
                                                <button th:type="submit">Proceed</button>
                                            </form>`
Output is
![image](https://user-images.githubusercontent.com/5524563/26937190-71ff33ae-4c90-11e7-894d-71af90061650.png)
Here parameter action is not listed on url.
I guess its due to _csrf parameter overriding my action parameter.
I am using 
Spring-boot 1.5.3 Release
along with Thymeleaf 3.0.1 Release
with Spring Security

**Comment by danielfernandez** [comment]
This is not Thymeleaf-related, but expected browser behaviour, as explained in the HTML5 specification. Form fields (in your case, `_csrf`) override any request parameters included in the query string of the URL specified in the `action` attribute of `<form>`.
