### ISSUE TITLE
can not direct to the @RequestMapping method by using Intellij Idea.

### ISSUE THREAD

**Issue by bks-abs** [thymeleaf/thymeleaf-spring#147]
I really like this template(thymeleaf-spring4), but could i mention a small request, when using IDEA, if I use this code, 
`<a th:href="@{/register}">hello</a>` 
I have no way to hold down the CTRL key to jump to the corresponding method up.

of course,use this code is OK,`<script th:src="@{/webjars/jquery/3.2.1/jquery.min.js}"></script>`.

 if someone can add this feature,I will bow to you every day.

**Comment by danielfernandez** [comment]
The Thymeleaf support in InteliiJ IDEA is developed and maintained by JetBrains themselves, the makers of IntelliJ. So I think you should add a ticket there in their support system to get the functionality you want…

**Comment by bks-abs** [comment]
I'm so foolish:)....and sorry to mention such a problem in the wrong place ^_^
