### ISSUE TITLE
ThymeleafReactiveView.renderInternal breaks with more than one ConversionService

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf-spring#149]
The current code for `ThymeleafReactiveView` obtains the `ConversionService` to be used at the `EvaluationContext` (for SpEL expressions in the view) like:

```java
        final ConversionService conversionService =
                applicationContext.getBeanNamesForType(ConversionService.class).length > 0?
                        applicationContext.getBean(ConversionService.class): null;
```

However, in some scenarios (like using Spring Cloud Stream, see https://github.com/spring-projects/spring-boot/issues/9727#issuecomment-314617308 ), there might be more than one `ConversionService` in the application context, and therefore this would fail.

A different strategy should be applied for looking the `ConversionService` up, maybe by bean ID or qualifier.

This *does not* affect the Spring MVC version.

**Comment by danielfernandez** [comment]
@gregturn could I know a bit more about this additional `ConversionService` added by Spring Cloud Stream? Am I right in understanding that it should be ignored for the execution of SpEL expressions at the view layer?

If so, it should be as simple as modifying the way in which `ThymeleafReactiveView` obtains this bean, which is by means of `applicationContext.getBeansForType(...)` (this is different to the Spring MVC version, in which the `ConversionService` comes as a request attribute). I'll look at how Spring Boot declares this bean for WebFlux, maybe simply selecting it by id could do…

**Comment by danielfernandez** [comment]
Apparently there would be two possibilities, judging from the code in `WebFluxConfigurationSupport` at https://github.com/spring-projects/spring-framework/blob/25f3aef1ab7aa2b6832dac637cb9d29a014909d7/spring-webflux/src/main/java/org/springframework/web/reactive/config/WebFluxConfigurationSupport.java#L319-L324

```java
@Bean
public FormattingConversionService webFluxConversionService() {
    FormattingConversionService service = new DefaultFormattingConversionService();
    addFormatters(service);
    return service;
} 
```

So either the *byType* request to `ApplicationContext` is narrowed down to `FormattingConversionService`, or it is done by name to `webFluxConversionService`.

Given the fact that the Spring MVC equivalent is called `mvcConversionService`, this ID seems pretty stable, and also `FormattingConversionService` could be used elsewhere by other pieces of (Spring) software, so probably the best option is to go for matching by ID on `webFluxConversionService`.

**Comment by gregturn** [comment]
Sounds like you have a solution in mind. I can test it when you release a new snapshot.

**Comment by danielfernandez** [comment]
Already in `3.0.7-SNAPSHOT`

**Comment by gregturn** [comment]
I just tested it out. Works great! Thanks.
