### ISSUE TITLE
Allow rendering of fragments directly (Spring3 requestmapping)

### ISSUE THREAD

**Issue by Antibrumm** [thymeleaf/thymeleaf-spring#15]
Hi
I am building currently a webapp with Spring 3 and Thymeleaf and I found it a bit annoying that we cannot return a fragment directly from the Controller. I have created an extended version of the ThymeleafViewResolver to allow this behavior and probably you there is some interest in this in the standard implementation?

I am not sure however if the method loadView is the appropriate point to!

return value (String or ModelAndView) may now be:
- "home/welcome" -> normal template
- "home/welcome :: message" -> ajax fragment (childOnly)
- "home/welcome :: message:full" -> ajax fragment (!childOnly)

<code>

```
@Override
protected View loadView(String viewName, Locale locale) throws Exception {

    String fragmentName = null;
    int index;
    if ((index = viewName.indexOf(" :: ")) != -1) {
        fragmentName = viewName.substring(index + 4);
        viewName = viewName.substring(0, index);
    }

    final AutowireCapableBeanFactory beanFactory = getApplicationContext()
            .getAutowireCapableBeanFactory();

    ThymeleafView view = (ThymeleafView) BeanUtils
            .instantiateClass(getViewClass());

    if (beanFactory.containsBean(viewName)) {
        final Class<?> viewBeanType = beanFactory.getType(viewName);
        if (AbstractThymeleafView.class.isAssignableFrom(viewBeanType)) {
            view = (ThymeleafView) beanFactory
                    .configureBean(view, viewName);
        } else {
            view = (ThymeleafView) beanFactory.initializeBean(view,
                    viewName);
        }
    } else {
        view = (ThymeleafView) beanFactory.initializeBean(view, viewName);
    }

    view.setTemplateEngine(getTemplateEngine());
    view.setTemplateName(viewName);
    view.setStaticVariables(getStaticVariables());

    if (!view.isContentTypeSet() && getContentType() != null) {
        view.setContentType(getContentType());
    }
    if (view.getLocale() == null && locale != null) {
        view.setLocale(locale);
    }
    if (view.getCharacterEncoding() == null
            && getCharacterEncoding() != null) {
        view.setCharacterEncoding(getCharacterEncoding());
    }

    if (fragmentName != null) {
        boolean childOnly = true;
        if ((index = fragmentName.indexOf(":full")) != -1) {
            childOnly = false;
            fragmentName = fragmentName.substring(0, index);
        }
        view.setFragmentSpec(new ElementAndAttributeNameFragmentSpec(null,
                "th:fragment", fragmentName, childOnly));
    }

    return view;

}
```

</code>

Else thumbs up. Nice TemplateEngine!

**Comment by danielfernandez** [comment]
Hmmm... this is a very nice idea! would you be willing to prepare a pull request for this?

The only thing I'm not sure about is that `fragment:full` syntax, as it is not used in any other parts of thymeleaf (include's, substituteby's or Tiles definitions...). At first impression, I think I prefer to leave this out. But the `view :: fragment` is a great idea, and should support both fragments defined with `th:fragment` and also DOM Selectors like in `view :: [//something/something]`.

Also, if you prepare a pull request, please make sure you read, follow and explicitly agree to https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.0.16/CONTRIBUTING.markdown

Thanks!

**Comment by Antibrumm** [comment]
Yes the full syntax is not ultra sexy. I just saw that childOnly flag and thought i allow using it somehow. We use it for rendering an ajax fragment for a table. It would be easy to simply left it out for the beginning and wrap the ajax template in another div.
I will have to test how to use the DOM selectors.

What about the location of the extension? loadView() seemed the easiest place at the time, but is it the correct one? I haven't dived into the caching mechanism yet, so my question is: I caching of the template applied as in the default behavior? 

I'll make a pull request and we see after.
