### ISSUE TITLE
A CSRF token may be given even in GET method.

### ISSUE THREAD

**Issue by yoshikawaa** [thymeleaf/thymeleaf-spring#150]
Using
----
#### Version of Thymeleaf
* thymeleaf-3.0.7.RELEASE
* thymeleaf-spring-3.0.7.RELEASE
#### Environment
* spring-boot-starter-parent-1.5.4.RELEASE

Demo
----
https://github.com/yoshikawaa/demo-thymeleaf-spring-issue150

Problem
----
When assigning `th: action` attribute to `form` element and not adding `method` attribute, a CSRF token is output regardless of get method. As follows.
```html
<form th:action="@{/sample}">
    <input type="submit" value="check" />
</form>
```
Output HTML
```html
<form action="web-application/sample">
    <input type="hidden" name="_csrf" value="22790eb6-4335-430d-ae1c-51415a65b569"/>
    <input type="submit" value="check" />
</form>
```
If submit, the CSRF token is exposed in the url parameter...orz

https://github.com/spring-projects/spring-security/blob/4.1.4.RELEASE/web/src/main/java/org/springframework/security/web/servlet/support/csrf/CsrfRequestDataValueProcessor.java#L36-L37
**I think it should not be outputted according to `DISABLE_CSRF_TOKEN_PATTERN`.**

Cause
----
https://www.w3.org/TR/html5/forms.html#attr-fs-method
HTML5 form default method is GET.

https://github.com/thymeleaf/thymeleaf-spring/blob/thymeleaf-spring4-3.0.7.RELEASE/thymeleaf-spring4/src/main/java/org/thymeleaf/spring4/processor/SpringActionTagProcessor.java#L103-L106
When method attribute is not found, `SpringActionTagProcessor` pass `null` as `httpMethod` to `RequestDataValueProcessor`.

https://github.com/spring-projects/spring-security/blob/4.1.4.RELEASE/web/src/main/java/org/springframework/security/web/servlet/support/csrf/CsrfRequestDataValueProcessor.java#L50
When passed `httpMethod` is `null`, `CsrfRequestDataValueProcessor` output a CSRF token.

Solution
----
When method attribute is not found, `SpringActionTagProcessor` should pass `GET`.

----
Please consider! Thanks.

**Comment by danielfernandez** [comment]
This is confirmed. The difference in behaviour with the Spring JSP tag library lies in the fact that, when the `<sf:form>` Spring tag is used with no `action` attribute, `POST` is used by default and added to the resulting `<form>` tag.

Thymeleaf does not create or rewrite the `<form>` tag, so directly reading the `action` value as it is being done now and using `GET` as a default for calling the `RequestDataValueProcesor` infrastructure seems indeed to be the sensible thing to do.

**Comment by danielfernandez** [comment]
Already in  `3.0.8-SNAPSHOT`
