### ISSUE TITLE
setCheckExistence of SpringResourceTemplateResolver  does not work in thymeleaf-spring5 3.0.7

### ISSUE THREAD

**Issue by hantsy** [thymeleaf/thymeleaf-spring#154]
Currently I am trying to use Spring Boot 2.0.0.M3, and used thymeleaf and freemarker in the same project. 

I added ` resolver.setCheckExistence(false);` explicitly in the `thymeleafTemplateResolver` bean. 

```java
    @Bean
    public SpringResourceTemplateResolver thymeleafTemplateResolver() {

        final SpringResourceTemplateResolver resolver = new SpringResourceTemplateResolver();
        resolver.setApplicationContext(this.ctx);
        resolver.setPrefix("classpath:/templates/");
        resolver.setSuffix(".html");
        resolver.setTemplateMode(TemplateMode.HTML);
        resolver.setCacheable(false);
        resolver.setCheckExistence(false);
        return resolver;

    }
```

It seems it does not work. 

When I access path http://localhost:8080/freemarker, it should skip it and hand the template resolver to freemarker engine. But it throws exceptions.

```
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/freemarker.html]")
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:235)

```

The sample code is located in https://github.com/hantsy/spring-reactive-sample/tree/master/mvc

**Comment by danielfernandez** [comment]
> I added `resolver.setCheckExistence(false);`

That should be `setCheckExistence(true)` to enable the check (which is disabled by default). If it does not check the existence of the template, it will consider it *resolvable* by default.

**Comment by hantsy** [comment]
Changed to `setCheckExistence(true)`, still encounter exceptions:

```
18:11:30.980 [reactor-http-nio-2] ERROR org.thymeleaf.TemplateEngine - [THYMELEAF][reactor-http-nio-2] Exception preparing throttled template "freemarker": Error resolving template "freemarker", template might not exist or might not be accessible by any of the configured Template Resolvers
org.thymeleaf.exceptions.TemplateInputException: Error resolving template "freemarker", template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:870)
	at org.thymeleaf.engine.TemplateManager.parseAndProcessThrottled(TemplateManager.java:757)
	at org.thymeleaf.TemplateEngine.processThrottled(TemplateEngine.java:1184)
	at org.thymeleaf.TemplateEngine.processThrottled(TemplateEngine.java:1158)
	at org.thymeleaf.spring5.SpringWebFluxTemplateEngine.lambda$createChunkedStream$1(SpringWebFluxTemplateEngine.java:257)
```
The web config class,

```java
@Configuration
@EnableWebFlux
class WebConfig implements ApplicationContextAware, WebFluxConfigurer {

    private ApplicationContext ctx;

    @Override
    public void setApplicationContext(ApplicationContext context) {
        this.ctx = context;
    }

    @Bean
    public FreeMarkerConfigurer freeMarkerConfig() {
        FreeMarkerConfigurer configurer = new FreeMarkerConfigurer();
        configurer.setTemplateLoaderPath("classpath:/templates/");
        return configurer;
    }

    @Bean
    public SpringResourceTemplateResolver thymeleafTemplateResolver() {

        final SpringResourceTemplateResolver resolver = new SpringResourceTemplateResolver();
        resolver.setApplicationContext(this.ctx);
        resolver.setPrefix("classpath:/templates/");
        resolver.setSuffix(".html");
        resolver.setTemplateMode(TemplateMode.HTML);
        resolver.setCacheable(false);
        resolver.setCheckExistence(true);
        return resolver;

    }

    @Bean
    public ISpringWebFluxTemplateEngine thymeleafTemplateEngine() {
        // We override here the SpringTemplateEngine instance that would otherwise be
        // instantiated by
        // Spring Boot because we want to apply the SpringWebFlux-specific context
        // factory, link builder...
        final SpringWebFluxTemplateEngine templateEngine = new SpringWebFluxTemplateEngine();
        templateEngine.setTemplateResolver(thymeleafTemplateResolver());
        return templateEngine;
    }

    @Bean
    public ThymeleafReactiveViewResolver thymeleafChunkedAndDataDrivenViewResolver() {
        final ThymeleafReactiveViewResolver viewResolver = new ThymeleafReactiveViewResolver();
        viewResolver.setTemplateEngine(thymeleafTemplateEngine());
        viewResolver.setOrder(1);
        viewResolver.setResponseMaxChunkSizeBytes(8192); // OUTPUT BUFFER size limit
        return viewResolver;
    }

    @Override
    public void configureViewResolvers(ViewResolverRegistry registry) {
        registry.viewResolver(thymeleafChunkedAndDataDrivenViewResolver());
        registry.freeMarker().suffix(".ftl");
    }

}


```

**Comment by danielfernandez** [comment]
Oh, sorry for my misunderstanding. The aim of the `setCheckExistence(boolean)` flag is to determine whether a **thymeleaf template resolver** should consider a template resolvable or not, passing control to the next template resolver (the next *thymeleaf template resolver*) if the template is not considered resolvable (in this case, by checking it does not exist). But this happens during Thymeleaf execution, because Thymeleaf can be configured several template resolution mechanisms.

But here we are not at the Thymelaf template resolver level, but rather at the Spring view resolution level, before Thymeleaf is executed at all. To control that at that level, and thus be able to pass execution to a completely different template engine, you need to use the `viewNames`/`excludedViewNames` patterns established at the `ViewResolver` itself so that it is Spring who selects FreeMarker instead of Thymeleaf for execution.

**Comment by hantsy** [comment]
OK, understand the purpose of setCheckExistence in  thymeleafTemplateResolver.

So I have to set `viewNames` to differentiate the various template engines, and why I can not separate them by the template file suffix?

I guest the correct process is, 
1. Check `/freemarker` in  path `/templates/freemarker.thml`, if it is not found, skip to render it, and pass the work in next view resolvers.
2. Check `/freemarker` in path `/templates/freemarker.ftl` , if found it , use freemarker engine to render the view.

**Comment by danielfernandez** [comment]
The `viewNames` property in Spring's `ViewResolver` instances applies on the view name returned by your controller. It is not until a specific template engine is being executed that a prefix + suffix is applied, so you need to make your view names themselves able to be differentiated.

**Comment by hantsy** [comment]
@danielfernandez I checked `FreemarkerView`, there is also a checkExistence method, but if catch `FileNotFoundException`,  it return a false there, never throw the exception.  In my impression the viewResovlers list should be ordered and executed as `chain`.
