### ISSUE TITLE
Thymeleaf-Spring5 unusable with WebFlux and Boot 2.0.0.M4

### ISSUE THREAD

**Issue by gregturn** [thymeleaf/thymeleaf-spring#156]
Thymeleaf-Spring5 3.0.8-SNAPSHOT is broken due to Spring Framework 5.0.0.RC4 moving encodeUrl out of ServerHttpResponse

**Comment by gregturn** [comment]
See https://github.com/spring-projects/spring-boot/issues/10319 for stack traces.

**Comment by danielfernandez** [comment]
This should be already fixed in `3.0.8-SNAPSHOT`. Does this snapshot work for you?

**Comment by gregturn** [comment]
Recent commit?

**Comment by danielfernandez** [comment]
Yesterday

**Comment by gregturn** [comment]
Thanks!

**Comment by gregturn** [comment]
Already patched in https://github.com/thymeleaf/thymeleaf-spring/commit/1ed59e8c06349bee73bc3d676c526d8d26e7fa10
