### ISSUE TITLE
Thymeleaf not rendering the text from message.properties file

### ISSUE THREAD

**Issue by suhasbhatta** [thymeleaf/thymeleaf-spring#158]
I am using ngDialog which shows the dialog. I used to pass a value from javascript to generate a dialog. It was pure english before and working fine without any error. But when i tried to use the th:text it is not rendering the value from properties file.

` this.showMsg = function (title,msg) {
        var dialog = ngDialog.open({
            template: '<div class="toast">\
            <div class="toast__icon text-info icon-info-circle"></div>\
                <div class="toast__body">\
            	<div class="toast__title">'+title+'</div>\
                <div class="toast__message">'+msg+'</div>\
            </div>\
            </div>',
            plain: true,
            showClose: false,
            overlay:false,
            className: 'ngdialog-theme-default'
        });
        setTimeout(function () {
            dialog.close();
        }, dialogTimeOut);
    };
` It works, but `this.showError = function (title,msg) {
        var dialog = ngDialog.open({
            template: '<div class="toast">\
            <div class="toast__icon text-danger icon-error"></div>\
                <div class="toast__body">\
            	<div class="toast__title">'+title+'</div>\
            	 <div class="toast__message" th:utext="#{'+msg+'}">'+msg+'</div>\
            </div>\
            </div>',
            plain: true,
            showClose: false,
            overlay:false,
            className: 'ngdialog-theme-default'
        });
        setTimeout(function () {
            dialog.close();
        }, dialogTimeOut);
    };` this will not work #

**Comment by danielfernandez** [comment]
Same as thymeleaf/thymeleaf#644
