### ISSUE TITLE
Multiple template resolvers not working correctly

### ISSUE THREAD

**Issue by nikhil-sahu** [thymeleaf/thymeleaf-spring#164]
While configuring a template engine with multiple template resolvers, the below configuration does not works

    @Bean
    public SpringTemplateEngine templateEngine() {
        SpringTemplateEngine templateEngine = new SpringTemplateEngine();
        templateEngine.addTemplateResolver(webTemplateResolver());
        templateEngine.addTemplateResolver(classLoaderTemplateResolver());
        return templateEngine;
    }

However, this works fine:

    @Bean
    public SpringTemplateEngine templateEngine() {
        SpringTemplateEngine templateEngine = new SpringTemplateEngine();
        Set<ITemplateResolver> resolvers = new HashSet<>();
        resolvers.add(webTemplateResolver());
        resolvers.add(classLoaderTemplateResolver());
        templateEngine.setTemplateResolvers(resolvers);
        return templateEngine;
    }

Ideally, they both should behave the same.
The first configuration uses only `webTemplateResolver` and does not fall back on the `classLoaderTemplateResolver`.

https://stackoverflow.com/questions/46601417/multiple-view-resolvers-not-working-with-thymeleaf

**Comment by danielfernandez** [comment]
Could you please also share the definition of your template resolvers, and specify your version of Thymeleaf?

**Comment by nikhil-sahu** [comment]
public ITemplateResolver classLoaderTemplateResolver() {
        ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();
        templateResolver.setPrefix("/templates/");
        templateResolver.setCacheable(false);
        templateResolver.setSuffix(".html");
        templateResolver.setTemplateMode(StandardTemplateModeHandlers.LEGACYHTML5.getTemplateModeName());
        templateResolver.setCharacterEncoding(StandardCharsets.UTF_8.name());
        return templateResolver;
    }

    @Bean
    public ITemplateResolver webTemplateResolver() {
        ServletContextTemplateResolver resolver = new ServletContextTemplateResolver();
        resolver.setPrefix("/public/");
        resolver.setSuffix(".html");
        resolver.setTemplateMode(StandardTemplateModeHandlers.LEGACYHTML5.getTemplateModeName());
        resolver.setCharacterEncoding(StandardCharsets.UTF_8.name());
        resolver.setCacheable(false);
        return resolver;
    }

I am using spring-boot `1.4.0` . I believe that's `thymeleaf-spring4`.

**Comment by nikhil-sahu** [comment]
ok. once I added the resolvable patterns to the view resolvers, either of above config is working alright. There might have been another reason (still eludes me) as to why that was not working previously(without adding resolvable patterns) but this doesn't seem to be the issue. Closing.
