### ISSUE TITLE
Transparently handle Java 8's Optional

### ISSUE THREAD

**Issue by hamishlawson** [thymeleaf/thymeleaf-spring#167]
It would make template code much cleaner if Thymeleaf's Spring dialect handled Java 8 Optionals transparently rather than obliging explicit calls to the likes of isPresent(), get() and orElse(). _vbezhenar_ in the thread below suggested a possible implementation, but didn't know how to get the converter added:

http://forum.thymeleaf.org/java-util-Optional-td4028258.html#a4028665

**Comment by odrotbohm** [comment]
I'd love to see this get priority as Java 8 seems to be pretty standard these days. Not sure that's a Spring module specific thing though.

**Comment by hamishlawson** [comment]
It would be good if it could also transparently handle Vavr's Option.

**Comment by danielfernandez** [comment]
Thymeleaf 3.1 will be Java 8-based, so for the moment I'm queueing this for that version.

**Comment by danielfernandez** [comment]
Moved this ticket to the core repository (copied, GH does not allow moving), as it actually belongs there given support should be more general than just the SpringStandard Dialect: thymeleaf/thymeleaf#672

Closing this one to avoid duplicity.
