### ISSUE TITLE
Documentation for #themes.code(...)

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf-spring#17]
We might want to document the new `#themes.code(...)` expression object somewhere in the Thymeleaf-Spring3 PDF so that Thymeleaf + Spring developers can know about it.

**Comment by danielfernandez** [comment]
Emanuel, could you add this yourself? Maybe just a new bullet in Chapter 2, below the explanation for `${beans.*}` could be enough...

**Comment by ultraq** [comment]
Done: 2f49ac1ef97d6a02fc56a836fe2e579e9f3987f8
I think I raised this issue back when I didn't know how we wrote and published our documentation.
