### ISSUE TITLE
templateEngine.process（...）has no return value.

### ISSUE THREAD

**Issue by Volcannozzz** [thymeleaf/thymeleaf-spring#172]
i want to process a html for emaill. but my code was blocked in <code>templateEngine.process(...)</code>.
here is my config:

	public void testTemplate()
	{
		try
		{
			Context context = new Context();
			context.setVariable("name", "vayne");
			System.out.println("begin.");
			String string = templateEngine.process("com/vayne/config/test.html", context);
			System.out.println("this is： " + string);
		}
		catch (Exception e) {
			e.printStackTrace();
		}
	}

run it and just get "begin.",then it is over,next there is no other output.of course ,i do not get "this is: xxx".

**Comment by danielfernandez** [comment]
There are many possible reasons for this: Maybe you are getting an `Error` (not an `Exception`) that you are not caching (try changing that `catch (Exception e)` to `catch (Throwable t)`), or maybe there is some kind of infinite loop in your template...

Without knowing more about your template and your application, there is no possible answer to be given, sorry.

**Comment by danielfernandez** [comment]
Closing due to reporter inaction.
