### ISSUE TITLE
th:field should render hidden field before checkbox to not break common checkbox replacements 

### ISSUE THREAD

**Issue by franktopel** [thymeleaf/thymeleaf-spring#178]
Almost all custom checkbox replacement solutions, be it in Bootstrap, Foundation or Materialize CSS, depend upon the following HTML structure:

`<input type="checkbox" id="my_id" />`
`<label for="my_id">Checkbox label</label>`

This is due to the limitations of CSS where usually the visual checkbox replacement is implemented like this:

```
input[type=checkbox] { visibility: hidden; width: 0; overflow: hidden; }
input[type=checkbox] + label::before { font-family: IconFont; content: "\e801"; }
input[type=checkbox]:checked + label::before { content: "\e802"; }
/* or some other unicode character or even an image */
```
(`+` meaning `adjacent sibling` or `subsequent direct neighbour`)

Which means the replacement can _only_ work if the `checkbox` comes **right before** the `label` element, with no further element between the two.

Of course CSS also has the `~` sibling selector, but using that would affect all subsequent labels within the same parent element, which is obvioulsy unwanted as it dictates the outer HTML structure.

There is no problem that you're adding a hidden field when using `th:field` and I clearly understand why you're doing it - the problem is the position you're inserting it. To not get in the way of custom checkbox replacements, would anything object against placing your `<input type="hidden" name="my_id" value="on" />` **before** the actual `<input type="checkbox" />`?

Note: I am aware of https://github.com/thymeleaf/thymeleaf-spring/issues/68 but the person closing that issue seemingly did not grasp the problem.

**Comment by dquessenberry** [comment]
I am also facing this exact problem and there doesn't appear to be a clean workaround without hacking my standardized CSS to support this specific use case. If anyone knows how to configure Thymeleaf to insert the hidden input BEFORE the checkbox input, please us know!

BTW, this appears to be the offending code: https://github.com/thymeleaf/thymeleaf-spring/blob/3.0-master/thymeleaf-spring5/src/main/java/org/thymeleaf/spring5/processor/SpringInputCheckboxFieldTagProcessor.java

**Comment by danielfernandez** [comment]
A new `boolean renderHiddenMarkersBeforeCheckboxes` configuration property has been added to `SpringStandardDialect`, and can be also configured directly from `SpringTemplateEngine`. So now you can do:

```java
SpringStandardDialect dialect = ...;
dialect.setRenderHiddenMarkersBeforeCheckboxes(true);
```

or:

```java
SpringTemplateEngine templateEngine = ...;
templateEngine.setRenderHiddenMarkersBeforeCheckboxes(true);
```

**Comment by danielfernandez** [comment]
Already in `3.0.10-SNAPSHOT`

**Comment by denneralmeida** [comment]
spring.thymeleaf.render-hidden-markers-before-checkboxes=true

set this in application.proprerties
