### ISSUE TITLE
Add JPMS automatic module names

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf-spring#179]
Adding `Automatic-Module-Name` entries to the `MANIFEST.MF` files of each thymeleaf-spring module will allow us to _reserve_ the module name for future use. See http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

Completely modularising the library could mean an issue for some scenarios as of today, as the jar file would contain at least one file (`module-info.class`) with Java 9 bytecode level, which can nowadays be troublesome. See http://blog.joda.org/2018/03/jpms-negative-benefits.html

There are at least two approaches to module naming (project-name-based and reverse-DNS-based, see [this](http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html), but we will go for project-based as it is simpler, and the approach recommended by Mark Reinhold (see [this](http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-February/000582.html)) and adopted by the Spring family of projects.

So module names will be `thymeleaf-spring3`, `thymeleaf-spring4` and `thymeleaf-spring5`.

**Comment by danielfernandez** [comment]
Already in `3.0.10-SNAPSHOT`

**Comment by panga** [comment]
@danielfernandez The module names set are not supported.
Please change the "-" with "." character.

See the error:
```
Unable to derive module descriptor for: thymeleaf-spring5-3.0.10.RELEASE.jar
Automatic-Module-Name: thymeleaf-spring5: Invalid module name: 'thymeleaf-spring5' is not a Java identifier
```
