### ISSUE TITLE
display Unescaped Text with th:placeholder or th:title etc.

### ISSUE THREAD

**Issue by squalou** [thymeleaf/thymeleaf-spring#184]
Hi,

I have an issue similar to this one : https://stackoverflow.com/questions/32501163/unescaped-text-with-thplaceholder/32515802#32515802

Using thymeleaf 3.0.9, I have a template that includes this 

`th:placeholder="${form.country}"`

When the value for country is `Pa&#237;` ... in the end the produced html is `&amp;#237;` which is not what anyone would expect.

I understand that for regular 'text' I can use 'th:utext', but for placeholder or others .. I didn't find any way to workaround this issue.

One suggestion was to use unicode sequences instead of html entities but that sounds really like a bad idea.

Thanks for any suggestion in case it's not a bug and I'm missing something.

Regards,
S

**Comment by danielfernandez** [comment]
Thymeleaf performs HTML-escaping of all HTML attributes being output through any of its attribute processors (`th:*`), like `th:placeholder`.

Escaping HTML for safe rendering is a responsibility of the view layer (the template engine), so Thymeleaf does not expect that the data itself in model is already escaped, being `th:utext` a special case used for performing unescaped rendering in the body of HTML tags. In this `th:placeholder` case, the fact that all attributes of HTML tags should be escaped is a specific rule of the chosen view style (HTML in this case), so it is at the view layer where this operation should be done.

Besides, input values and placeholders do not allow renderable HTML tags as a value (you cannot make something _bold_ in a text input, for instance), so IMHO it wouldn't make much sense to allow unescaped rendering in this context…
