### ISSUE TITLE
Design Flaw on fragments/layouts

### ISSUE THREAD

**Issue by yhojann-cl** [thymeleaf/thymeleaf-spring#192]
Formerly in thymeleaf 2 it was possible to use a base layout for all the fragments but in thymeleaf 3 it is only possible to make inclusions, but where is the problem?

The problem is that it is no longer possible to create designs of a single file, forcing a separation between the different contents, for example, it is no longer possible to have two fragments in a single layot ​​using a single template because now it is necessary to create the header, intermediate content and footer, have forced us to make a sandwich of files.

Normally in a Software development as it was done naturally in other Frameworks such as MVC5 / Razor, User Controls (design containers) and others, the design container was a single one, which included the necessary fragments called by the controller, for which the fragment of the section of the WEB site was much cleaner. The design problem is that each fragment must manually include all the structured files of the template (header, footer, slides, sidebar, etc), if it is required to make a change in the template it will also be necessary to modify all the fragments, this Change can lead to design integrity problems, and directly impacts the scalability of a software development because if multiple groups of developers work on the same project, they will have to constantly modify their fragments every time the template change, this is totally unnatural.

**Comment by jmiguelsamper** [comment]
There are many ways to set up hierarchical templates, see https://www.thymeleaf.org/doc/articles/layouts.html for a detailed discussion and examples

**Comment by danielfernandez** [comment]
> Formerly in thymeleaf 2 it was possible to use a base layout for all the fragments but in thymeleaf 3 it is only possible to make inclusions, but where is the problem?

I'll just add that Thymeleaf never had a hierarchical layout fragment system as such (though in Thymeleaf 3 it can be simulated, in fact). In order to do so in Thymeleaf 2 you had to use the LayoutDialect (which is a separate project, and has a version for thymeleaf 3) or something totally different such as Apache Tiles.
