### ISSUE TITLE
Fix Automatic-Module-Name

### ISSUE THREAD

**Issue by panga** [thymeleaf/thymeleaf-spring#195]
https://github.com/thymeleaf/thymeleaf-spring/issues/179 broke the JPMS compatibility adding invalid characters in the Automatic-Module-Name.

Please change the "-" with "." character.

Error:

```
Unable to derive module descriptor for: thymeleaf-spring5-3.0.10.RELEASE.jar
Automatic-Module-Name: thymeleaf-spring5: Invalid module name: 'thymeleaf-spring5' is not a Java
```

**Comment by panga** [comment]
cc @danielfernandez

**Comment by danielfernandez** [comment]
You're right, thanks. Will probably need to apply some kind of (Groovy?) script during build in order to perform that transformation.

**Comment by danielfernandez** [comment]
Already in `3.0.11-SNAPSHOT`

**Comment by danielfernandez** [comment]
Already in `3.0.11-SNAPSHOT`

**Comment by panga** [comment]
Awesome! Thank you!
