### ISSUE TITLE
Non-blocking resolution of variables assumes mutable model

### ISSUE THREAD

**Issue by bclozel** [thymeleaf/thymeleaf-spring#196]
The following commit (3601af0b2) assumes that the `Map` model provided by Spring Framework is mutable (it is not). This has been raised and is currently discussed in [SPR-17407](https://jira.spring.io/browse/SPR-17407).

**Comment by danielfernandez** [comment]
Definitely a bug, Thymeleaf should make no assumptions about that map being mutable.

However, this has not shown up in any of our tests. Am I right in thinking an immutable map would only be passed by the _functional_ webflux framework?

**Comment by bclozel** [comment]
Yes, AFAIK this is only enforced in WebFlux, and we're not likely to change that on the MVC side right now.

**Comment by danielfernandez** [comment]
No, I mean in the functional side only. We have tests with WebFlux (non-functional) and they work alright...

**Comment by bclozel** [comment]
Ah, silly me. Yes you're right, this is done on the functional side only with `DefaultRenderingResponseBuilder`.

**Comment by danielfernandez** [comment]
Already in `3.0.11-SNAPSHOT`
