### ISSUE TITLE
AbstractView is receiving an immutable model Map

### ISSUE THREAD

**Issue by yiss** [thymeleaf/thymeleaf-spring#197]
Spring Boot version: 2.0.6.RELEASE

Using Thymeleaf to render a view throws a java.lang.UnsupportedOperationException: null

Here is the stack trace :
[Log](https://textuploader.com/dnplp)

**Comment by danielfernandez** [comment]
Thanks a lot. Actually this was reported just minutes before at #196 too, so I'm going to close this one in order to avoid duplicity.
