### ISSUE TITLE
ConcurrentModificationException during stress test

### ISSUE THREAD

**Issue by H-Lo** [thymeleaf/thymeleaf-spring#217]
Hi!
Tried to do stress test on my project and when issuing many requests on the page rendered with Thymeleaf, the exception is throws.
Version: Name	thymeleaf-spring5-3.0.9.RELEASE.jar
Please see attached files for more info.

The template is not attached because my point is to make error logging to make some sense - just throwing exception that says nothing is the same as the exception is ignored.
Please try to add some information to log before throwing this exception.
From the stack trace you'll see the place where to put additional checks and log outputs.
It would be really great to see template line where the exception occured.

BR,
Hrvoje

[exception.txt](https://github.com/thymeleaf/thymeleaf-spring/files/3326717/exception.txt)

[pom.xml.txt](https://github.com/thymeleaf/thymeleaf-spring/files/3326720/pom.xml.txt)

**Comment by danielfernandez** [comment]
As you already stated in the ticket's title, the cause is a `ConcurrentModificationException` :
```
ERROR ... [THYMELEAF][http-nio-8080-exec-3] Exception processing template "index": An error happened during template parsing (template: "class path resource [templates/index.html]")
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "class path resource [templates/index.html]")
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:241) ~[thymeleaf-3.0.9.RELEASE.jar:3.0.9.RELEASE]
	at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100) ~[thymeleaf-3.0.9.RELEASE.jar:3.0.9.RELEASE]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:666) ~[thymeleaf-3.0.9.RELEASE.jar:3.0.9.RELEASE]
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098) [thymeleaf-3.0.9.RELEASE.jar:3.0.9.RELEASE]
...
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
	at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:276) ~[thymeleaf-3.0.9.RELEASE.jar:3.0.9.RELEASE]
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) ~[thymeleaf-3.0.9.RELEASE.jar:3.0.9.RELEASE]
	at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) ~[thymeleaf-3.0.9.RELEASE.jar:3.0.9.RELEASE]
```

In Java, this is an error that is typically issued by iterators if the collection they are iterating is modified during iteration (and those iterators don't support concurrent modifications). So I'm guessing you have a `th:each` in your `index.html` that iterates an `ArrayList` that is modified while iteration is taking place.

As a side note, it's not that Thymeleaf does not add a message to the `ConcurrentModificationException`. Thymeleaf never throws that exception, it's the `ArrayList` object you are using who does, and it throws it without a message. Check the JDK's code here: http://hg.openjdk.java.net/jdk8/jdk8/jdk/file/tip/src/share/classes/java/util/ArrayList.java#l886

**Comment by H-Lo** [comment]
Hi Daniel,

Thank you for your answer!!

I am aware od base cause of ConcurrentModificationException and I did some code inspect. But as I have approx 10 iterators on my template, that means I have to remove them all and add one by one, and maybe also many combinations as only 1st and 3rd and so - to check which one is the problem.
During "normal" usage on localhost an my Java hosting (without many requests per second) - everything work well. My guess is something is not thread safe but for now I don'w know what it is.

Also I know that Thymeleaf does not throw this exception as it is visible in stack trace - but it would be great if you could catch it, add additional info e.g. "template name: xxx, line: yyy, iterator name: zzz" and rethrow it. Is that scenario possible? That would help not only my project but any other experiencing the same issue.

Thanks!

BR,
Hrvoje

**Comment by danielfernandez** [comment]
Thymeleaf does output line and column information for exceptions whenever it is possible. But unfortunately in some cases when the template cache is not enabled (which seems to be your case) insertion of fragments has to go through the parser again, and line+col information is lost.

I would suggest turning template cache back on for a while. That should give you line and column for your exception.

**Comment by H-Lo** [comment]
Thank you very much!
I'll try with cache for sure!
My (wrong) idea was that not using cache could be more verbose when it comes to error logging.
Thanks!
