### ISSUE TITLE
About layout, how to keep actions performed on the menu, in a new browser tab or window, with Thymeleaf and Spring?

### ISSUE THREAD

**Issue by ezequielllbarbosa** [thymeleaf/thymeleaf-spring#220]
For example, in the GMAIL layout, let's suppose now I'm seeing the contents of the "inbox" and in parallel, in the side menu, the "category" menu was opened. Then if I open a new browser tab or window with the exact same URL, the "category" menu remains open (last action). How to do this with Thymeleaf and Spring? Is there somewhere a code snippet with this example? I looked at some things about Thymeleaf (fragment) and Ajax, but didn't see an example that would fit 100% when I open a new tab or window.

Step 1, Viewing the Inbox

Step 2, seeing the "inbox" and just opening the "category" menu (note the URL doesn't change)

Step 3, open a new tab, then put in the same URL as in step 1 and the page result is same life as in step 2

**Comment by ultraq** [comment]
This seems like a more general web development question rather that just Spring/Thymeleaf.

Out of curiosity, I opened my browser tools on Gmail and followed your steps to see what happens, and I think they're storing your last viewing preference on the server side.  Every time I expand/collapse the Categories menu, a network request is made that contains some JSON model that could possibly be the updated view structure.  So when I open Gmail in a new tab, the server can load the last viewing preference that was submitted to inform the page to look a particular way when it opens.

**Comment by ezequielllbarbosa** [comment]
Many thanks @ultraq 

I really liked this possibility. When I send to server, I think a lot about form submit, but in this case it seems not necessary. Is there an example (with code) in this case involving network request, JSON, thymeleaf and Spring?
