### ISSUE TITLE
Mvc.MethodArgumentBuilderWrapper: implement/propagate encode() method

### ISSUE THREAD

**Issue by mschuerig** [thymeleaf/thymeleaf-spring#224]
In Spring5, MvcUriComponentsBuilder.MethodArgumentBuilder has the new method encode(). Please add this to Mvc.MethodArgumentBuilderWrapper.

See https://github.com/spring-projects/spring-framework/issues/21565 for the reasoning.

**Comment by danielfernandez** [comment]
An `.encode()` method has been added to `#mvc`, but please note that `MvcUriComponentsBuilder.MethodArgumentBuilder#encode()` might not be working as expected.

Please have a look at this test: https://github.com/thymeleaf/thymeleaf-tests/blob/a45ed5d01bdb2f257b52c32e60b54ebeb29ca9f4/src/test/resources/templateengine/springintegration/mvc/mvc02.thtest#L17-L18

From my understanding of how this `encode()` method should work, the `+` in query parameter values should be encoded, but apparently from what I see at the Spring code, only the base URL is being encoded. Is this an issue in Spring or maybe I am misunderstanding something?

**Comment by danielfernandez** [comment]
BTW you can use `3.0.12-SNAPSHOT` already for testing this if you want.
