### ISSUE TITLE
dead?

### ISSUE THREAD

**Issue by Captain-P-Goldfish** [thymeleaf/thymeleaf-spring#234]
Is thymeleaf dead?
no commits for more than a year

**Comment by jmiguelsamper** [comment]
Hello,

thanks for your interest and your concerns.

It is true that the development of Thymeleaf has slowed down during the last years but I consider it a very stable project. It is currently used in thousands of production sites, many of them with huge traffic figures, with no known issues.

Please note that Thymeleaf is comprised of several subprojects and some of them are more active than others. There is also some development happening behind the scenes.

Being an open-source project with no external funding, it is only driven by altruist contributions, so we cannot commit to any timeline for the future roadmap.

Please use your own best judgement to decide it the Thymeleaf is good for your project or not.
