### ISSUE TITLE
DeferredResult broke html hints

### ISSUE THREAD

**Issue by robertmakrytski** [thymeleaf/thymeleaf-spring#245]
Spring version is 2.4.0.
Can't define hints or can't define variable in html code when use DeferredResult<String>.
I can see the red lines under variables that i add to model in controller with  DeferredResult<String>
![image](https://user-images.githubusercontent.com/10616325/102006775-c7866700-3d34-11eb-9f93-b9b40bcae07e.png)

**Comment by danielfernandez** [comment]
Sorry, is this a Thymeleaf issue or maybe you are talking about your IDE? If this something that is not working for you in Thymeleaf itself, could you be more specific?

**Comment by robertmakrytski** [comment]
1)the code works well. 
2)I used last intellIJ.
But i want to see fields of object
![image](https://user-images.githubusercontent.com/10616325/102022673-62189180-3d99-11eb-8b24-13521e4d6a29.png)

**Comment by danielfernandez** [comment]
Sorry, the Thymeleaf plugin for IntelliJ is developed by Jetbrains themselves, not us. You should open a ticket with them.
