### ISSUE TITLE
Time down when load edit form with select that contain several options.

### ISSUE THREAD

**Issue by faker-ben-ali** [thymeleaf/thymeleaf-spring#259]
For exemple we have societe select input (binded to an object with societe property)  **with thousand societes** for detecting **selected value by thymeleaf** (if not null ) it make 100 sql request .
Suppose forms that contains more than select it cause  page  timedown load.

**Comment by danielfernandez** [comment]
This is not a Thymeleaf issue, but of the way form binding has been programmed in your Spring web application.
