### ISSUE TITLE
upgrading thymeleaf-spring5 to 3.0.13.RELEASE keeps using thymeleaf 3.0.13.RELEASE

### ISSUE THREAD

**Issue by jonnytest1** [thymeleaf/thymeleaf-spring#270]
i updated our pom.xml to 3.0.13.RELEASE for thymeleaf-spring5 and ran Maven  > Upgrade Project (should be the same as mvn clean package -U)

this upgraded thymeleaf-spring5 correctly but kept using version 12 for thymleaf causeing exceptions
( org.thymeleaf.spring5.dialect.SpringStandardDialect tried to access private fieldorg.thymeleaf.standard.StandardDialect.conversionService (org.thymeleaf.spring5.dialect.SpringStandardDialect and org.thymeleaf.standard.StandardDialect are in unnamed module of loader 'app' )

as a workaround i actively excluded thymeleaf and added the dependency myself

```
	<dependency>
		<groupId>org.thymeleaf</groupId>
		<artifactId>thymeleaf-spring5</artifactId>
		<version>3.0.13.RELEASE</version>
		<exclusions>
			<exclusion>
				<artifactId>thymeleaf</artifactId>
			</exclusion>
		</exclusions>
	</dependency>
	<dependency>
		<groupId>org.thymeleaf</groupId>
		<artifactId>thymeleaf</artifactId>
		<version>3.0.13.RELEASE</version>
	</dependency>
```

**Comment by danielfernandez** [comment]
Sorry, this is some kind of issue in your project's dependency tree, IDE or build system.

The `thymeleaf-spring5-3.0.13.RELEASE` artifact correctly references `thymeleaf-3.0.13.RELEASE` as you can see at the Maven repo itself: https://repo1.maven.org/maven2/org/thymeleaf/thymeleaf-spring5/3.0.13.RELEASE/thymeleaf-spring5-3.0.13.RELEASE.pom

```xml
<dependency>
  <groupId>org.thymeleaf</groupId>
  <artifactId>thymeleaf</artifactId>
  <version>3.0.13.RELEASE</version>
  <scope>compile</scope>
    <exclusions>
      <exclusion>
        <groupId>ognl</groupId>
        <artifactId>ognl</artifactId>
      </exclusion>
    </exclusions>
</dependency>
```

**Comment by Ltadrian** [comment]
Same issue with me as well:
+- org.thymeleaf:thymeleaf-spring5:jar:3.0.13.RELEASE:compile
[INFO] |  \- org.thymeleaf:thymeleaf:jar:3.0.12.RELEASE:compile
[INFO] |     +- org.attoparser:attoparser:jar:2.0.5.RELEASE:compile
[INFO] |     \- org.unbescape:unbescape:jar:1.1.6.RELEASE:compile

Issue occurs locally, and on jenkins server when building our service. I run into the same error message.
@danielfernandez
