### ISSUE TITLE
Version 3.0.13+ IlegalAccessError

### ISSUE THREAD

**Issue by CNeenan** [thymeleaf/thymeleaf-spring#273]
When upgrading to version 3.0.13+ we are seeing IllegalAccessError exception 

```
class org.thymeleaf.spring5.dialect.SpringStandardDialect tried to access private field org.thymeleaf.standard.StandardDialect.conversionService
```

Within the class SpringStandardDialect.java in package org.thymeleaf.spring5.dialect

I can see the issue in this method, it is not able to access the conversionService field:

```
    @Override
    public IStandardConversionService getConversionService() {
        if (this.conversionService == null) {
            this.conversionService = new SpringStandardConversionService();
        }
        return this.conversionService;
    }
```

**Comment by danielfernandez** [comment]
The `conversionService` property in `StandardDialect` was modified to `protected` for 3.0.13 as you can see here: https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-3.0.13.RELEASE/src/main/java/org/thymeleaf/standard/StandardDialect.java#L134

I suspect you are mixing jars of both 3.0.13 and 3.0.12 versions.
