### ISSUE TITLE
How to Get HTTP Request & User Credentials From Thymeleaf v3 Processor?

### ISSUE THREAD

**Issue by geoffblandrbs** [thymeleaf/thymeleaf-spring#283]
We are upgrading from Thymeleaf v2 to Thymeleaf v3.

We use many processors for a lot of custom tags we have in our templates - one of the great benefits of Thymeleaf is that it can be customised like this.

We have several processors that need to determine the user/role for the request to determine how to process and what HTML to output. A simple example is an Announcement processor that outputs HTML for announcements that a given user hasn't seen or outputs nothing if the user has seen them all. 

With Thymeleaf v2 we subclassed `AbstractMarkupSubstitutionElementProcessor` and used the `getMarkupSubstitutes()` Arguments to extract the `SpringWebContext`, from that get the `HttpServletRequest` and from that extract the credentials and get the user.

Something like this:

```
protected List<Node> getMarkupSubstitutes(Arguments aArguments, Element aElement) {

		SpringWebContext context = (SpringWebContext) aArguments.getContext();
		HttpServletRequest request = context.getHttpServletRequest();
		AbstractAuthenticationToken credentials = getCredentials(aRequest);
		String username = getOperatorName(credentials); 
...

```
Now with Thymeleaf v3 we implement `IElementModelProcessor` and the code seems a lot cleaner. 

But how do we get at the `SpringWebContext` and `HttpServletRequest` with this interface. 

From the `IElementModelProcessor.process()` call we get the `ITemplateContext`, `IModel` and `IElementModelStructureHandler` but I can't see how to drill down into these to get the `SpringWebContext` or `HttpServletRequest`.

I think I must be missing something simple.

**Comment by ultraq** [comment]
For `HttpServletRequest`, I've found that the `ITemplateContext` that you're given is an instance of a `WebEngineContext` (https://www.thymeleaf.org/apidocs/thymeleaf/3.0.15.RELEASE/org/thymeleaf/context/WebEngineContext.html) which has a `getRequest` method on it that returns the `HttpServletRequest`, so you may need to do some casting but the request should be there.

As for `SpringWebContext`, I believe this is now `SpringWebMcvThymeleafRequestContext` can be obtained calling `SpringContextUtils.getRequestContext()` (https://www.thymeleaf.org/apidocs/thymeleaf-spring5/3.0.15.RELEASE/org/thymeleaf/spring5/context/SpringContextUtils.html#getRequestContext(org.thymeleaf.context.IExpressionContext)).  It returns an `IThymeleafRequestContext`, but the implementation will be a `SpringWebMvcThymeleafRequestContext` for Spring Web MVC projects.

**Comment by geoffblandrbs** [comment]
@ultraq Sorry, took a while to test this as I got tied up in other things. I can confirm this works - thanks for the advice.

I would be helpful if  this was documented somewhere as I would expect many users of ThymeLeaf would be doing this. Am I right that currently the only documentation on how to customise ThymeLeaf with Dialects and Processors is just the comments in the request for the v3 changes - is there no other documentation on this? Have I missed some documentation somewhere?

**Comment by ultraq** [comment]
Going through the Thymeleaf docs page (https://www.thymeleaf.org/documentation.html), there is the "Extending Thymeleaf" tutorial on the website (https://www.thymeleaf.org/doc/tutorials/3.0/extendingthymeleaf.html).  A quick glance through it makes me think the focus is more on the Thymeleaf objects given to custom processors like the structure handler and working with Thymeleaf model objects for manipulating the DOM, as opposed to obtaining things like the servlet or spring web contexts.
