### ISSUE TITLE
Autowired not working for own View classes (extending ThymeleafView)

### ISSUE THREAD

**Issue by rainerfriesen** [thymeleaf/thymeleaf-spring#30]
Like discussed in the [Thymeleaf User Forum](http://forum.thymeleaf.org/Autowired-not-working-for-own-View-classes-td4026691.html) there seems to be an issue with the usage of custom View classes (extending ThymeleafView) and autowired properties.

The problem occurs if the view bean is not known to the application context, what should normally not be the case, and an autowired property is used. In that case the view bean is initialized using the initializeBean method which does not autowire the annotated properties.

A possible solution is already mentioned in the forum entry.

Kind Regards,
Rainer

**Comment by danielfernandez** [comment]
Updated 2.0.19-SNAPSHOT and 2.1.0-SNAPSHOT
