### ISSUE TITLE
Why doesn't th:checked work with th:field?

### ISSUE THREAD

**Issue by ShedowSith** [thymeleaf/thymeleaf-spring#302]
There is such a block of code for displaying checkboxes:

`<th:block th:each="type:${types}">
  <label class="list-group-item">
    <input class="form-check-input me-1" type="checkbox" th:value="${type.getId()}" th:field="*{types}" 
        th:checked="${selectType.contains(type)}">
    <span th:text="${type.name}"></span>
  </label>
</th:block>`

On form load the checkboxes are not set as selected, if I remove th:field everything is displayed, but without th:field I can't pass the form data to the controller. What is the problem?

**Comment by ultraq** [comment]
Looking at the checkbox examples in the docs (https://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html#checkbox-fields), it looks like what you need to get a checkbox backed by form data is `th:field` and `th:value`.  A `checked` attribute will be added by Thymeleaf if the value is considered selected/`true`, so you don't need to provide one yourself.

Given that, your `<input>` might need to look more like the following:

```html
<input class="form-check-input me-1" type="checkbox" th:field="*{types}" th:value="${type}">
```

I found another example here, part 2.3, which includes how it all lines up with the backing bean: https://frontbackend.com/thymeleaf/working-with-forms-in-thymeleaf

**Comment by ShedowSith** [comment]
thanks a lot, everything worked. It turns out that the field that I pass to th : field should contain an array of selected elements
