### ISSUE TITLE
Thymeleaf 3.1.1 with SpringMVC 6.0.3 and Tomcat 10

### ISSUE THREAD

**Issue by Paul9194637** [thymeleaf/thymeleaf-spring#309]
Herer is xml setting Thymeleaf 3.0 with SpringMVC 4 MVC and Tomcat 7and JDK 11,  it is workable, 
my question is how set with Thymeleaf 3.1.1 with SpringMVC 6.0.3 and Tomcat 10 and JDK 19 in xml for render .html

<bean id="viewResolver" class="org.thymeleaf.spring5.view.ThymeleafViewResolver">
        <property name="order" value="1"/>
        <property name="characterEncoding" value="UTF-8"/>
        <property name="templateEngine">
           <bean class="org.thymeleaf.spring5.SpringTemplateEngine">
               <property name="templateResolver">
                   <bean class="org.thymeleaf.spring5.templateresolver.SpringResourceTemplateResolver">
                       <property name="prefix" value="/WEB-INF/templates/"/>
                       <property name="suffix" value=".html"/>
                       <property name="templateMode" value="HTML5"/>
                       <property name="characterEncoding" value="UTF-8"/>
                   </bean>
               </property>
           </bean>
        </property>
    </bean>

**Comment by danielfernandez** [comment]
Since Thymeleaf 3.1, this `thymeleaf-spring` repository is no longer used. Please have a look at the example applications in the `thymeleaf` repository here: https://github.com/thymeleaf/thymeleaf/tree/3.1-master/examples

**Comment by Paul9194637** [comment]
thank you for your quickly reply, but I just study Java Spring MVC with Thymeleaf, I cannot understand your example code.
Here is my code and build from your example code, it cannot show hello now, I have no idea about that.
Please help to check if you have free time. anyway, thanks your help.
https://github.com/Paul9194637/thymeleaf-examples-spring6-sayhello

**Comment by Paul9194637** [comment]
excuse me, I republished all project, here is the link
https://github.com/Paul9194637/springMVC

**Comment by Paul9194637** [comment]
after study, I can understand your simple code and use thymeleaf with Spring 6 MVC on Tomcat 10, thanks your support.
