### ISSUE TITLE
Big Performance Drop on a mix of th:with + ${beans.xxxx}

### ISSUE THREAD

**Issue by Rouche** [thymeleaf/thymeleaf-spring#35]
Situation:
I had lots of pages using the same template. After refactoring all those pages to avoid repeating the base template everywhere (in 2.1.0 this will be even nicer) i decided to remove all the repeated ModelAttributes and put it in the base template using th:with.

So zero code change in html.

basically:

``` html
<body th:with="domainValues=${beans.domainValues}">
   everything else.
</body>
```

Time to load a page with @ModelAttribute("domainValues") : around 0.150 sec,

Time to load page with the local variable on body tag : 2.8 seconds.

-bean is singleton and never reinitialized
-trace log is the same
-domainValues is used around 500+ times around the template with substitutes by, each loops, etc.

Question is... why such a difference? This variable should behave the same as a ModelAttribute?

Big question is... is using th:with, a very bad idea performance wise for any situation?

Regards.

**Comment by danielfernandez** [comment]
Using `th:with` in your scenario should not provoke a significant difference.

Using this application context: https://github.com/thymeleaf/thymeleaf-tests/blob/20140506/src/test-21/resources/engine21/springintegration/applicationContext-beans.xml which defines a bean like:

``` xml
  <util:map id="domainValues">
    <entry key="one" value="ONE1" />
    <entry key="two" value="TWO2" />
    <entry key="three" value="THREE3" />
    <entry key="four" value="FOUR4" />
    <entry key="five" value="FIVE5" />
    <entry key="six" value="SIX6" />
    <entry key="seven" value="SEVEN7" />
    <entry key="eight" value="EIGHT8" />
    <entry key="nine" value="NINE9" />
    <entry key="ten" value="TEN10" />
    <entry key="eleven" value="ELEVEN11" />
    <entry key="twelve" value="TWELVE12" />
    <entry key="thirteen" value="THIRTEEN13" />
    <entry key="fourteen" value="FOURTEEN14" />
    <entry key="fifteen" value="FIFTEEN15" />
  </util:map>
```

...we created four tests that simulate four different scenarios:

**Scenario 1**

Use `th:with`. Access with `${beans.domainValues}` (old, 2.0-style access):

``` xml
<body th:with="domainValues=${beans.domainValues}">
```

File: https://github.com/thymeleaf/thymeleaf-tests/blob/20140506/src/test-21/resources/engine21/springintegration/beans/beans02.thtest

**Scenario 2**

Use `th:with`. Access with `${@domainValues}` (2.1-style access, more integrated with SpringEL):

``` xml
<body th:with="domainValues=${@domainValues}">
```

File: https://github.com/thymeleaf/thymeleaf-tests/blob/20140506/src/test-21/resources/engine21/springintegration/beans/beans03.thtest

**Scenario 3**

Do _not_ use `th:with`. Access with `${@domainValues}`:

``` xml
<li th:each="domainValue : ${@domainValues}" ...>
```

File: https://github.com/thymeleaf/thymeleaf-tests/blob/20140506/src/test-21/resources/engine21/springintegration/beans/beans04.thtest

**Scenario 4**

Do _not_ use `th:with`. Add bean to context (like `@ModelAttribute`). Access with `${domainValues}`

``` xml
<li th:each="domainValue : ${domainValues}"
```

File: https://github.com/thymeleaf/thymeleaf-tests/blob/20140506/src/test-21/resources/engine21/springintegration/beans/beans05.thtest

**Results**

Executing each option 1000 times (after a warmup period), preliminary results show no really remarkable difference between the four options -- at least not as remarkable as your _20x_:

```
[SCENARIO 1] BENCHMARK EXECUTED IN 5803266752ns (5803ms)
[SCENARIO 2] BENCHMARK EXECUTED IN 4301671676ns (4301ms)
[SCENARIO 3] BENCHMARK EXECUTED IN 5010886992ns (5010ms)
[SCENARIO 4] BENCHMARK EXECUTED IN 5096711714ns (5096ms)
```

Maybe your domain objects were very large? Were they many?

**Comment by Rouche** [comment]
Hi,

Unfortunatelly my contract ended i dont have access to the code anymore.
And i had to switch on JSF (sadly)

The bean was a manual Java class. With like 20 getXXX methods returning
about 10 elements average.

The bean was declared by annotation in WebConfig. Used in the same web page
around 20 times. Sometime, the same property used 3 time (Like
state/province for 3 different address)

I was also incredibly surprised to find such a big performance issue. The
object is exactly the same, so the issue was not the access time inside the
object itself. Just declared differently.

Maybe it got fixed by a side effect? Oh well, at least there was a
workaround!

Thanks.

JF

**Comment by Rouche** [comment]
Actually in your scenario 1.

It should be something like:

<body th:with="domainValues=${beans.domainValues}">

<ul>

<li th:each="stateProv : ${domainValues.stateProvince}">

</ul

Maybe thats why it gets a performance issue, the getStateProcinve()
method on domain values gets evaluated each time?

**Comment by danielfernandez** [comment]
Nope, it's only evaluated once for that `th:each`. Its result is a collection/array, and then such collection/array is iterated. Just one evaluation of the expression.
