### ISSUE TITLE
Field information should be exposed together with the error-message

### ISSUE THREAD

**Issue by opensource21** [thymeleaf/thymeleaf-spring#36]
It would be good not to get only the message of an error. There should be additional the information which field has this error.
See http://forum.thymeleaf.org/How-to-get-all-errors-of-a-form-including-the-information-which-field-has-the-error-td4026950.html#a4026952

**Comment by danielfernandez** [comment]
This has been implemented as:

``` html
<ul>
    <li th:each="e : ${#fields.detailedErrors()}" th:class="${e.global}? globalerr : fielderr">
        <span th:text="${e.global}? '*' : ${e.fieldName}">The field name</span> |
        <span th:text="${e.message}">The error message</span>
    </li>
</ul>
```

The `#fields.detailedErrors()` method returns a `List<DetailedError>`, being `DetailedError` this class: https://github.com/thymeleaf/thymeleaf-spring3/blob/69a0fd2b33238ecac9b0a49c1b52b6121d39f9af/src/main/java/org/thymeleaf/spring3/util/DetailedError.java

Messages are already applied their respective parameters and localization artifacts.

**Comment by danielfernandez** [comment]
Updated 2.1.2-SNAPSHOT
