### ISSUE TITLE
Avoid applying RequestDataValueProcessor in Spring 4 RC

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf-spring#42]
Given the fact that the `RequestDataValueProcessor` interface in Spring has been modified in Spring 4.0 RC, thymeleaf-spring3 should avoid applying the support for this interface when Spring version is 4.0, in order to avoid runtime errors.

This will disable CSRF protection support for Spring 4.0 RC, but at least it will allow Spring 4 betatesters to use `thymeleaf-spring3` until Spring 4.0.0.RELEASE is published and a corresponding `thymeleaf-spring4` module is created.

**Comment by danielfernandez** [comment]
Updated 2.1.2-SNAPSHOT

**Comment by odrotbohm** [comment]
Is there a way to work around this problem until 2.1.2 is released? I just ran into this trying to render a Spring Security login page through a Thymeleaf template. All other pages render fine. Is there an estimated release date for 2.1.2?

**Comment by danielfernandez** [comment]
You can use 2.1.2-SNAPSHOT following the instructions here: http://www.thymeleaf.org/faq.html#use-snapshot

Anyway, 2.1.2 should be released no later than next Monday Dec 9.

**Comment by odrotbohm** [comment]
Unfortunately I can't use the snapshots, as the update will have to make it into a release tomorrow. Any other idea of why this is working for all of the renderings except the Spring Security one? Next week for 2.1.2 sounds like a bearable time frame :).

**Comment by danielfernandez** [comment]
This should be failing whenever thymeleaf encounters a `th:field`, `th:method`... basically, any of the uses of `RequestDataValueProcessor` described here: https://github.com/thymeleaf/thymeleaf-spring3/issues/7#issuecomment-27643488

This only happens when Spring 4.0RC is being used. If you are not directly using Spring 4... maybe the version of Spring Security you are using includes the Spring 4 version of `RequestDataValueProcessor` as a dependency somehow?

> Unfortunately I can't use the snapshots, as the update will have to make it into a release tomorrow. 

OK, there's only one task left at the 2.1.2 backlog, and it's rather small. So maybe we can reorganize tasks and try to push it a bit to have 2.1.2 by tomorrow. Would that help?

**Comment by odrotbohm** [comment]
That's been very useful. I simply went with a plain `action="…"` now and that works fine for me. So no need to hurry with the 2.1.2. Thanks for the quick turnaround!

**Comment by danielfernandez** [comment]
FYI, Thymeleaf 2.1.2 was released today :)

**Comment by odrotbohm** [comment]
Awesome, Daniel… thanks for the ping! :)

**Comment by gaaschk** [comment]
Excellent!

Kevin Gaasch
Java Developer
LinkedIn Profile
Online Calendar: Tungle.Me
Cell: 806.674.1523
