### ISSUE TITLE
How do I set view previx outside of src/main/webapp?

### ISSUE THREAD

**Issue by trusktr** [thymeleaf/thymeleaf-spring#58]
So for example, I have the following in my servlet-context.xml:

```
    <beans:bean id="templateResolver"
        class="org.thymeleaf.templateresolver.ServletContextTemplateResolver">
                <beans:property name="prefix" value="/../java/edu/csus/csc191/views/" />
        <beans:property name="suffix" value=".html" />
        <beans:property name="templateMode" value="HTML5" />
        <!-- Template cache is set to false (default is true). -->
        <beans:property name="cacheable" value="false" />
    </beans:bean>
```

the value of

```
<beans:property name="prefix" value="/WEB-INF/views/" />
```

indicates that my view folder is located in `src/main/webapp/WEB-INF/views`. How would I move my view folder outside of `src/main/webapp`?

For example, how would I move it to `/src/main/foobar`?

I tried doing 

```
<beans:property name="prefix" value="/../foobar/views/" />
```

but that didn't work, and it give the error

> SEVERE: Servlet.service() for servlet [appServlet] in context with path [/hp-dsat] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template "v2_upload", template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause

so using the realtive `/../` doesn't work. Is there some way to put my view folder outside of `src/main/webapp`?

**Comment by ultraq** [comment]
You can use a different template resolver, like a `ClassLoaderTemplateResolver` or `FileTemplateResolver`, to be able to search for templates in different locations.  You're probably best served by the `ClassLoaderTemplateResolver` since you want to search your classpath.
