### ISSUE TITLE
Modify default output character encoding

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf-spring#60]
It seems Spring will modify the default character encoding as of 4.1: https://jira.spring.io/browse/SPR-11779

Thymeleaf should mirror this behaviour, and set UTF-8 as default if Spring is version 4.1 or higher.

**Comment by kelokelo** [comment]
They do not change. Task has status won't fix.

**Comment by danielfernandez** [comment]
You're right. Thanks. Closing this, at least for now.
