### ISSUE TITLE
@DateTimeFormat ignored inside th:each loop

### ISSUE THREAD

**Issue by arienkock** [thymeleaf/thymeleaf-spring#62]
This works: ${{page.content[**${itemStat.index}**].startTime}}
but using ${{item.startTime}} does not.

I have no explicitly defined ConversionService, only the default FormatterRegistry available through @EnableWebMvc

**Comment by danielfernandez** [comment]
Are you using a version older than 2.1.3.RELEASE? Please have a look at #49.

**Comment by arienkock** [comment]
Oops, I was not. Thanks for the heads up.
