### ISSUE TITLE
th:field should set raw value when input type is number or range.

### ISSUE THREAD

**Issue by divinespear** [thymeleaf/thymeleaf-spring#67]
Currently, `th:field` always apply formatters automatically.

when `<input>` type is `number` or `range`, and field has formatter (mostly `@NumberFormat`), formatted value is not number, so ignored by browsers.
it should set raw value instead formatted value when `<input>` type is `number` or `range`.

**Comment by danielfernandez** [comment]
At first thought this looks like a good idea. Let me think a bit more about the consequences of this, anyway, because the Spring JSP TagLib does not do this (it does apply `@NumberFormat`) and I'd like to be sure that such change does not break anything.

**Comment by danielfernandez** [comment]
This has finally been implemented, as can be seen in the linked commit.

Updated 2.1.4-SNAPSHOT.

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this improvement.
