### ISSUE TITLE
Form checkbox handling with dynamic fields

### ISSUE THREAD

**Issue by mreiterer** [thymeleaf/thymeleaf-spring#71]
I am using dynamic fields for a generic way to present entities. The actual values are in a map. 

``` java
public class GenericEntity {
    protected Map<String, Object> properties = new LinkedHashMap<String, Object>();

```

Here is a snipped from my template: 

``` html
<form th:object="${entity}" th:method="post" th:action="@{${#httpServletRequest.servletPath}}" id="add-entity-form" class="form-horizontal" role="form">

<div th:each="column : *{tableConfiguration.getColumns()}" class="form-group">
<input th:type="checkbox" th:field="*{properties[__${column.name}__]}" />

```

The checkbox is not bound correctly when using the pre-processing which is necessary for my dynamic fields.
Means: no hidden field is generated for spring mvc, the value in the map is not used to render the checked attribute of the input field.

**Comment by danielfernandez** [comment]
I think you are missing single quotes in your expression. Shouldn't...

``` html
<input th:type="checkbox" th:field="*{properties[__${column.name}__]}" />
```

actually be:

``` html
<input th:type="checkbox" th:field="*{properties['__${column.name}__']}" />
```

?

**Comment by mreiterer** [comment]
The approach works in general, also spring mvc databinding to the map. What i have to do manually is to convert the fields to the desired datatype.

The resulting html is: 

``` html
<input type="checkbox" id="propertiesvdp" name="properties[vdp]" value="" />  
```

Your approach produces: 

``` html
<input type="checkbox" id="properties&#39;vdp&#39;" name="properties[&#39;vdp&#39;]" value="" />  
```

Still no databinding, still no hidden field for spring mvc.

**Comment by mreiterer** [comment]
my current workaround is:

``` html
    <input th:type="checkbox" th:name="|properties[${column.name}]|" th:value="true" th:checked="${entity.properties[__${column.name}__]}"/>
    <input type="hidden" th:name="|_properties[${column.name}]|" value="on" />   
```

**Comment by danielfernandez** [comment]
I've added tests for this at https://github.com/thymeleaf/thymeleaf-tests/blob/288e58800b4825ce5a7f630ba088928c37f66fa8/src/test-21/resources/engine21/springintegration/form/form10.thtest (also see https://github.com/thymeleaf/thymeleaf-tests/blob/288e58800b4825ce5a7f630ba088928c37f66fa8/src/test-21/resources/engine21/springintegration/form/form10.thtest ) and it works OK (adding the single quotes, which are required per the SpringEL syntax, see http://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html#expressions-properties-arrays ).

Does your workaround work for you, even without the quotes? Do you have a public _getter_ method for your `properties` field?

**Comment by mreiterer** [comment]
Thanks for effort and support. 

Yes. i have a public getter method. 
And yes - the workaround works OK without quotes.

1) I do not understand your test - shouldn't the output include a hidden field with underscore prefix for spring mvc ?

2) Can you add a test with a boolean property ? 

entity.properties['boolField'] = true
Then i would expect the checked property set for the checkbox.

**Comment by danielfernandez** [comment]
OK. The problem is in `th:type`. For some reason this works OK if you use `type` instead (which, by the way, you don't have any reason not to use). Will investigate this as a bug.

**Comment by mreiterer** [comment]
Confirmed. Thanks. I am using th:type because i determine the type dynamically.

**Comment by danielfernandez** [comment]
Fixed!

Updated 2.1.4-SNAPSHOT
