### ISSUE TITLE
Error when applying conversion to expression that looks like a bean property

### ISSUE THREAD

**Issue by pjentsch** [thymeleaf/thymeleaf-spring#72]
When using the "{{bean.property}}" notation to apply conversion in spring expressions with expressions like "{{bean.someMethod()}}", rendering fails with a NotReadablePropertyException. 

I assume that's because "FieldUtils#isBound" checks only if the bean is present, but not if the property path is valid. 

I hacked up a sample project that displays the bug, available at https://github.com/pjentsch/thymeleaf-converter-problem

**Comment by danielfernandez** [comment]
Fixed by applying #73 

Updated 2.1.4-SNAPSHOT

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this fix.
