### ISSUE TITLE
Possibility to bind errors via th:field value

### ISSUE THREAD

**Issue by ravshansbox** [thymeleaf/thymeleaf-spring#74]
Is it possible to bind error via th:field value?
Instead of

```
<input th:field="*{fieldName}" th:class="${#fields.hasErrors('fieldName')}? 'error'" />
```

better would be this

```
<input th:field="*{fieldName}" th:errorClass="'error'" />
```

otherwise pages often contain some tens of ${#fields.hasErrors('fieldName')}

**Comment by danielfernandez** [comment]
Actually, the `th:errorclass` attribute exists since Thymeleaf 2.1.0, and it works exactly as you describe :-)

**Comment by ravshansbox** [comment]
good to know, thank you very much.
