### ISSUE TITLE
[Bootstrap + Thymeleaf + Spring] Issue with radio buttons

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf-spring#79]
Hi all, 
I'm doing a project where I'm using bootstrap (v. 3.3.2) and thymeleaf (spring-boot-starter-thymeleaf), everythings looks to be good but I'm having some issues when I want to pre-check a radio button while I'm loading info in the radio groups.

I try to use th:attr and th:checked; but I don't see any results (I don't see the "checked" property in the input element).  But, I did an experiment with th:multiple and th:selected, and in this cases I can see the attribute showing up in the html.

I found this issue that looks very similar a what I have:
https://github.com/thymeleaf/thymeleaf-spring/issues/29

The group of radios display all the information, but I never see the checked property in the input.  I'm using the latest stable version of both libraries.

Here is my code (please see that the input is inside of a label):

```
<div class="btn-group" data-toggle="buttons">
                <label th:each="feature : ${featureList}" th:for="${#ids.next('features')}"
                    th:class="${feature.id == 1} ? 'btn btn-default active' : 'btn btn-default'">
                    <input type="radio" name="myRadios" th:field="*{features}"                      
                        th:text="${feature.name}" th:value="${feature.id}" 
                        th:checked="${feature.id == 1}" />
                </label>
            </div>
```

This is important because this code is inside of a form, and I need to have that information at the server side; a workaround will be to check the input using javascript; however I will like to see if I can solve it by using thymeleaf or maybe is a mistake that I have.

Thanks in advance for the support

**Comment by mehanika** [comment]
Hi, have you tried removing `th:checked`?. Thymeleaf by itself will check the radio button if the corresponding value is in `*{features}`

**Comment by danielfernandez** [comment]
`th:field`, when applied on an `<input type="radio">`, automatically assigns values to the `checked` attribute (basically sets or unsets it as needed) based on the `value` (or `th:value` if exists) attribute. So, as @mehanika correctly points out, your `th:checked` there is interfering with the value assigned by `th:field`.
