### ISSUE TITLE
Use (optionally) the SpringEL compiler in Spring 4.1

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf-spring#84]
Spring 4.1 introduced compilation of SpringEL expressions: http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/expression/spel/standard/SpelCompiler.html

Expressions seem to be compiled using info from past executions, so it seems nothing needs to be done at the `PropertyAccessor` level as happens in OGNL. However this also means that some expressions might provoke runtime errors if they are used to resolve objects of diverse types (and the compiler has already computed the expected type for such expression). This means that somehow we should allow to enable/disable SpEL expression compilation as a configuration item.

**Comment by jkuipers** [comment]
Note that Andy Clement left a comment in https://jira.spring.io/browse/SPR-12271 suggesting that Spring might make some changes to prevent libraries like Thymeleaf having to change their code to make it suitable for SpEL compilation:

> VariablesMapPropertyAccessor is not compilable, it is a custom accessor. If it implemented CompilablePropertyAccessor rather than just PropertyAccessor we would call it to generate byte code. I've been wondering if there is a more general (though probably slower performing) solution to this we could do in Spring. Probably worth putting a bit of thought into this before forcing them to implement CompilablePropertyAccessor.

**Comment by danielfernandez** [comment]
This has been implemented as explained in #95
