### ISSUE TITLE
Setting message source in SpringTemplateEngine.

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf-spring#9]
Hi

Set custom message source in SpringTemplateEngine (via setMessageSource method) not working in web application because spring container reset message source with default one (that one with bean name "messageSource" in context). Then template engine working with different message source then one configured before.

**Comment by danielfernandez** [comment]
Fixed in 2.0.15 by adding a `setTemplateEngineMessageSource(MessageSource)` that serves as an override of the Spring default behaviour (determined by the `MessageSourceAware` interface).

Thanks.
