### ISSUE TITLE
ThymeleafViewResolver could check if the viewName/template exists

### ISSUE THREAD

**Issue by yacota** [thymeleaf/thymeleaf-spring#94]
It would be useful that ThymeleafViewResolver would use the ApplicationContext to check if the viewName exists in its canHandle method.
This feature would be very useful when using LiteDeviceDelegatingViewResolver with enableFallback set to true thus making it possible to use whenever possible the most appropiate view depending on the request's device type.

There are some things to take into account in order to do that :
- ThymeleafViewResolver needs to check if any registered TemplateResolver can locate the template
- ThymeleafViewResolver has to be aware that viewName could be something like fragment_footer::fragment
- ThymeleafViewResolver should ignore viewNames that starts with REDIRECT_URL_PREFIX or FORWARD_URL_PREFIX (in fact I think that ThymeleafViewResolver.createView method should first
  check for those patterns before calling canHandle)

Here is the snippet that we are currently using

```
protected boolean   canHandle(String viewName, Locale locale) {
    // here we return true to let ThymeleafViewResolver.createView method perform its logic, but as said before I think that createView logic order should be reordered
    if (viewName.startsWith(REDIRECT_URL_PREFIX) || viewName.startsWith(FORWARD_URL_PREFIX)) return true;

    if(!super.canHandle(viewName, locale)) return false;

    for(ITemplateResolver resolver: getTemplateEngine().getTemplateResolvers()) {
            // by now all the ITemplateResolver s are also TemplaterResolver s
            TemplateResolver templateResolver = (TemplateResolver) resolver;
            String prefix = templateResolver.getPrefix();
            String suffix = templateResolver.getSuffix();
            // Remove the include part if the view is an include
            String viewNameFinal = removeFragmentDetail(viewName);
            Resource res = applicationContext.getResource(prefix + viewNameFinal + suffix);
            if(res != null && res.exists()) return true;
        }
    }
    return false;
}


private String removeFragmentDetail(String viewName) {
    String cleanedViewName = viewName;
    if(viewName != null) {
        int indexColons = viewName.indexOf("::");
        if (indexColons > -1) {
            cleanedViewName = viewName.substring(0, indexColons).trim();
        }
    }
    return cleanedViewName;
}
```

I could make a PR if this is a desired feature

**Comment by SnakeSVx** [comment]
Would it not be better to add a canHandle method to each template resolver, and let each template resolver check internally if it can handle that specific view or not? 

This way it is more extendable, since not every resolver his resources might be able to be found through the applicationContext.

**Comment by yacota** [comment]
+1 I agree, but I still think that ThymeleafViewResolver.createView method should first check the existance of forward and redirect pattern before calling canHandle

**Comment by danielfernandez** [comment]
FYI, in relation to this, we are currently in the process of performing a large refactoring on the context, template resolution and message resolution APIs which, among other things, will bring the possibility to configure template resolvers to check the real existence of resources before considering them _resolved_.

**Comment by danielfernandez** [comment]
Please note that the `ITemplateResource#exists()` method (see thymeleaf/thymeleaf#419) and the `AbstractTemplateResolver#checkExistence` configurable flag should cover the need for template resolvers being able to check if a resource really exist before considering it _resolved_.

I'm leaving this open just in case doing something from the Spring view resolver is feasible, though at first thought it looks a bit complex to me... we'd have to somehow be able to resolve the resource _before_ actually calling `TemplateEngine#process(...)`, and that is not possible right now... we'll see.

**Comment by danielfernandez** [comment]
Several things to note regarding this ticket:
- Thanks to the new `ITemplateResource#exists()` method and the `AbstractTemplateResolver#checkExistence` flag Thymeleaf 3.0 allows to configure a chain of `ITemplateResolver`s that can skip to the next element in the chain by checking whether a resolvable template resource actually exists or not.
- It would be complex, especially (but not only) from a performance standpoint, to make `ThymeleafViewResolver` actually check resources by manually executing the above mechanism _before_ calling the `TemplateEngine`. Most cases would end up in a resource being resolved twice when only once was needed (template not cached) or once when no resolution was needed at all (template cached).
- After implementing #81, `redirect:` and `forward:` are now by default checked before executing `canHandle(...)`.

From your previous comments I understand this solution should be enough to support your scenario in Thymeleaf 3.0, and I'm therefore closing this ticket.

Thanks!

**Comment by yacota** [comment]
Awesome. Thanks !
